### ISSUE TITLE
Add warning when the required version does not match

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff-vscode#142]
When the required version does not match the current version of Ruff, VSCode fails silently.
I had this problem for multiple projects, and I only realized Ruff was not linting code with `pre-commit`.
It would really help to have a warning to diagnose this problem.

**Comment by charliermarsh** [comment]
Is this equivalent to [`required-version`](https://beta.ruff.rs/docs/settings/#required-version)?

**Comment by JonathanPlasse** [comment]
I use `required-version` in `pyproject.toml`.

**Comment by charliermarsh** [comment]
Ah, I see, the request is that we show a dedicated warning in VS Code rather than treating it as a generic failure.

**Comment by JonathanPlasse** [comment]
Yes, currently it is only visible in the Ruff output tab.

**Comment by adam-azarchs** [comment]
Even better would be if it was smart enough to use the correct version, at least when configured to use a "bundled" version of `ruff`.

**Comment by JonathanPlasse** [comment]
How would you do this, installing the correct version automatically?

**Comment by adam-azarchs** [comment]
That's what `pre-commit` does (in a venv).  It's true that that's not exactly "bundled" any more.

TBH I'd be satisfied with an option to have `ruff` ignore the `required-version` in `pyproject.toml` when VsCode is running it.  As it is, in a project with a large number of developers, right now most of them will have a silently non-functional extension most of the time, given how often `ruff` updates.  Running the wrong version isn't ideal but it's better than nothing.

**Comment by JonathanPlasse** [comment]
Should this be closed now that error messages are displayed?
