### ISSUE TITLE
Sort Imports works when isort is installed

### ISSUE THREAD

**Issue by vasudev-gm** [astral-sh/ruff-vscode#151]
The speed of linting is amazing and was amazed at the speed and memory requirements when using Ruff-Vscode on multiple instances of Vscode on linux. But I am facing weird issue since Sort Imports button doesn't do anything on Windows Vscode portable x64 edition using Python 3.11.2 x64.

Code Snippet:

```
import datetime
import json,ast
from random import randint

a: int = randint(0, 1000)
b: int = randint(0, 1000)

def add(a: int, b: int) -> int:
    return a + b

def subtract(a: int, b: int) -> int:
    if a > b:
        return a - b
    return b - a

if __name__ == "__main__":
    print(f"a={a}, b={b}")
    print(f"Addition operation of {a},{b}:{add(a,b)}")
    print(f"Subtraction operation of {a},{b}:{subtract(a,b)}")
    print(f"Datetime of the test run:{datetime.datetime.now()}")
```
Trace log:
```
[Trace - 10:55:00 PM] Received response 'textDocument/codeAction - (11)' in 2ms.
Result: [
    {
        "title": "Ruff: Organize Imports",
        "kind": "source.organizeImports",
        "diagnostics": [],
        "data": "file:///e%3A/Code/test/ruff_test.py"
    },
    {
        "title": "Ruff: Fix All",
        "kind": "source.fixAll",
        "diagnostics": [],
        "data": "file:///e%3A/Code/test/ruff_test.py"
    },
    {
        "title": "Ruff (F401): Remove unused import",
        "kind": "quickfix",
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 1,
                        "character": 16
                    },
                    "end": {
                        "line": 1,
                        "character": 20
                    }
                },
                "message": "`time` imported but unused",
                "severity": 2,
                "code": "F401",
                "source": "Ruff",
                "tags": [
                    1
                ],
                "data": {
                    "content": "",
                    "message": "Remove unused import",
                    "location": {
                        "row": 2,
                        "column": 0
                    },
                    "end_location": {
                        "row": 3,
                        "column": 0
                    }
                }
            }
        ],
        "edit": {
            "documentChanges": [
                {
                    "textDocument": {
                        "uri": "file:///e%3A/Code/test/ruff_test.py",
                        "version": 6
                    },
                    "edits": [
                        {
                            "range": {
                                "start": {
                                    "line": 1,
                                    "character": 0
                                },
                                "end": {
                                    "line": 2,
                                    "character": 0
                                }
                            },
                            "newText": ""
                        }
                    ]
                }
            ]
        },
        "data": "file:///e%3A/Code/test/ruff_test.py"
    }
]

```

![image](https://user-images.githubusercontent.com/54883603/224561058-16fd9eb0-080b-445d-8688-2a5490deeab0.png)

With isort installed I get the option to use either Ruff's Sort import or isort vscode. Any idea why this is happening on Windows?

![image](https://user-images.githubusercontent.com/54883603/224561132-2c821276-971a-44e8-8948-2d614c3e9167.png)

**Comment by charliermarsh** [comment]
Thank you! Just trying to understand the desired behavior / issue here a little bit better. Are you wondering why the unsorted imports doesn't appear as a lint error inline, like the unused imports? Or are you saying that you see `Ruff` as an option in the `Sort Imports` tab when running on Linux, but not on Windows?

**Comment by vasudev-gm** [comment]
Thank you Charlie for getting back. Sort Imports doesn't work but using Ctrl + Shift + P and Organize Sorts sorts imports.The odd thing is the same things works flawlessly on Linux.

**Comment by charliermarsh** [comment]
Does "Sort Imports" show up in the sidebar at all? Is it absent, or does it show up, but have no effect?

(I'm wondering if this is a version thing. I don't see "Sort Imports" in my VS Code.)

**Comment by vasudev-gm** [comment]
> Does "Sort Imports" show up in the sidebar at all? Is it absent, or does it show up, but have no effect?
> 
> (I'm wondering if this is a version thing. I don't see "Sort Imports" in my VS Code.)

Sorry I forgot to reply. It seems after updating 1.76.1 the issue is present in Windows and linux as well. I just needed to reboot and the issue came back. It seems VScode 1.76.1 changed the source.OrganizeImports setting works.

**Comment by vasudev-gm** [comment]
@charliermarsh I was searching for open issues/tickets there seems to be two of them opened a month ago.
[https://github.com/microsoft/vscode/issues/174295](url)
[https://github.com/microsoft/vscode/issues/173736](url)

**Comment by JonathanPlasse** [comment]
The links are broken.
- microsoft/vscode#174295
- microsoft/vscode#173736

**Comment by charliermarsh** [comment]
(It works fine for me on 1.76.2 so I'm not sure that it's related to the VS Code version.)

**Comment by vasudev-gm** [comment]
> (It works fine for me on 1.76.2 so I'm not sure that it's related to the VS Code version.)

That's really odd. Maybe I'll temporarily install isort until this is resolved from vscode.

**Comment by JonathanPlasse** [comment]
I add the same problem, it is now working for me with 1.76.2.

**Comment by JonathanPlasse** [comment]
Do you use the pre-release of isort?

**Comment by thoughtfuldata** [comment]
I am only using Ruff, i previously had isort installed

**Comment by vasudev-gm** [comment]
I tried pre-release version of both Python+pylance+isort+ruff on latest version 1.77 and still Organize imports works only when isort is installed and enabled, otherwise VSCode asks to install isort extension if not installed and ruff tries to sort/organize imports.

**Comment by charliermarsh** [comment]
I looked at this again, and I think it might actually be impossible for Ruff to work with that right click-to-"Sort imports" workflow. It seems like VS Code makes you use isort for that action (#16227, #8358).

**Comment by marcelomendoncasoares** [comment]
Don't know if its related, but I also had isort installed and have uninstalled to use only Ruff. I was facing a similar problem around here and found this configuration to be messing with the sort imports on save behavior

![image](https://github.com/astral-sh/ruff-vscode/assets/6807059/861e29fe-8546-4d1b-8b44-d1bef30141f0)

Wierdly enough, if I change it manually to the same value on the configurations JSON, it fixes the problem.

![image](https://github.com/astral-sh/ruff-vscode/assets/6807059/f1847b7b-276c-43fa-a904-e294c368e5c7)

Didn't investigate much further to undestand why if fixes, but I reverted to test and confirmed that this was the fix (in my case).

**Comment by vasudev-gm** [comment]
That's true. Even I started using the same JSON config system wide few months ago. Till now it works like a charm.
Actually thought only I faced this weird issue. Glad it's working now.
________________________________
