### ISSUE TITLE
Header must provide a Content-Length property

### ISSUE THREAD

**Issue by Roccoriu** [astral-sh/ruff-vscode#153]
When I try to use ruff, I get the following issue:
![image](https://user-images.githubusercontent.com/25778176/224774892-741a63b2-ac38-49fd-a2ef-399dc87a77e5.png)

I have installed the extension manually from the vsix file. (The Linux x64 version)
My VS Code version is: 1.76.1
The VS Code instance is running in a Docker container, and I'm using the remote ssh extension to develop on that container. 
What could be causing this issue?

**Comment by Roccoriu** [comment]
Linting does not work, nor do any of the other functions offered by this extensions. I have tried setting the interpreter path and ruff path manually, but it doesn't work either.

**Comment by charliermarsh** [comment]
I'm guessing that error is a red herring and there's some other issue underlying it.

**Comment by Roccoriu** [comment]
Probably, I noticed it happens every time I try to restart the server though. Do you have any tips on how I could debug this?

**Comment by charliermarsh** [comment]
I would try taking a look at the Output tab:

![Screen Shot 2023-03-13 at 2 09 56 PM](https://user-images.githubusercontent.com/1309177/224790994-8c703b0f-ac23-4c4b-b990-e64a9a1e5755.png)

**Comment by Roccoriu** [comment]
Unfortunately nothing else. The exact same issue is being displayed here: 
![image](https://user-images.githubusercontent.com/25778176/224793256-27ae5aa9-a062-4838-82bf-51519eff90d7.png)

**Comment by charliermarsh** [comment]
Closing for now to keep the Issue Tracker actionable.
