### ISSUE TITLE
Ruff uses local `attr` instead of bundled `attr 22.2.0`

### ISSUE THREAD

**Issue by YulienPohl** [astral-sh/ruff-vscode#159]
version:
- ruff: ruff-2023.8.0-win32-x64
- python: 3.9.15
- attr: 22.1.0

config:
```json
"ruff.importStrategy": "useBundled"
```

error:
```
ImportError: cannot import name 'AttrsInstance' from 'attr' 
(C:\ProgramData\miniforge3\lib\site-packages\attr\__init__.py)
```

**Comment by zhengyu-yang** [comment]
@charliermarsh I think you need to add the bundled lib directory to `PYTHONPATH` to ensure the bundled modules take priority. I also encountered the same error right now as my environment contains outdated version of `attrs`.

**Comment by charliermarsh** [comment]
Hmm, so we _do_ do that when the program initializes:

```py
# Update sys.path before importing any bundled libraries.
def update_sys_path(path_to_add: str) -> None:
    """Add given path to `sys.path`."""
    if path_to_add not in sys.path and os.path.isdir(path_to_add):
        sys.path.insert(0, path_to_add)


# Ensure that we can import LSP libraries, and other bundled libraries.
update_sys_path(os.fspath(BUNDLE_DIR / "libs"))
```

**Comment by charliermarsh** [comment]
I still don't understand how this is possible. 🤔

**Comment by YulienPohl** [comment]
Really strange. I also have `attrs` installed, but its sys module path gets changed?
```
'attr': <module 'attr' from 'C:\\ProgramData\\miniforge3\\lib\\site-packages\\attr\\__init__.py'>
'attrs': <module 'attrs' from 'C:\\Users\\Yulie\\.vscode\\extensions\\charliermarsh.ruff-2023.20.0-win32-x64\\bundled\\libs\\attrs\\__init__.py'>
```

**Comment by charliermarsh** [comment]
My best guess is that another extension is loading attrs, and so Python is using that cached module rather than our bundled version. But, I thought the extensions were sandboxed? If they’re not, it makes it impossible to have any guarantees around versioning at all. I need to do some testing.

**Comment by charliermarsh** [comment]
(To be clear, we want the version that’s bundled in the .vscode folder.)

**Comment by charliermarsh** [comment]
In some of your examples above, you use `attr` instead of `attrs`? Is that a mistake? Are those the actual errors?

**Comment by YulienPohl** [comment]
It comes from `attr`.
VSCode error: The Ruff server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by charliermarsh** [comment]
I'm at a loss, somehow `attr` is being imported before the extension runs. If I could reproduce, I may be able to help, but right now, I'm stuck.

**Comment by YulienPohl** [comment]
I have found the reason for this error.
I use `usercustomize.py` to have the `rich` pretty console every time Python starts up.

**Comment by charliermarsh** [comment]
Ohhh wow, thanks for following up.

I mean, we _could_ clear `sys.modules` at startup, which would've avoided this problem but could cause other unexpected problems.
