### ISSUE TITLE
"source.fixAll.ruff" doesn't work

### ISSUE THREAD

**Issue by Andy-Dihong-Luo** [astral-sh/ruff-vscode#160]
To disable other extentions running on save, I added `"source.fixAll.ruff = true"` to `settings.json` as  instructed, which however also disables Ruff's autofix as well.

**Comment by oyarsa** [comment]
+1. `source.fixAll.ruff` doesn't work either.

**Comment by thoughtfuldata** [comment]
`source.organizeImports.ruff:True`  Doesnt work for me as well. it only works without the `.ruff` I don't have isort or black-formatter  installed. I also check with and without `editor.FormatOnSave: true`

**Comment by frankwiles** [comment]
I also struggled with this a little bit yesterday and today.  Here is what worked for me: 

```
   ... 
   "[python]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.organizeImports": true,
        },
        "editor.formatOnType": true,
    },
   "editor.formatOnSave": true,
   "python.formatting.provider": "black",
   "python.formatting.blackPath": "/Users/frank/.pyenv/shims/black",
   ...
```

My issue was that I was overriding (twice) the formatter in the Workspace settings and didn't realize it!
