### ISSUE TITLE
Format Document and Format cell functionality

### ISSUE THREAD

**Issue by thoughtfuldata** [astral-sh/ruff-vscode#168]
Any plans to utilize those three right-click options in the future? 

Right now, I have to press save for Ruff to work.

**Comment by charliermarsh** [comment]
We don't plan to run Ruff on the "Format" action -- it runs as part of the "Source: Fix all" action (which seemingly isn't exposed on right-click, but is exposed in the Command Palette. I think is is as-intended. When we introduce the Ruff formatter, it will run on "Format".

<img width="801" alt="Screen Shot 2023-06-16 at 4 00 52 PM" src="https://github.com/astral-sh/ruff-vscode/assets/1309177/bf3b5d83-1470-4f9e-8c36-d121e5b2179b">
