### ISSUE TITLE
`python.linting.ignorePatterns` setting is not used

### ISSUE THREAD

**Issue by majutsushi** [astral-sh/ruff-vscode#175]
It would be really useful if the `python.linting.ignorePatterns` VS Code setting would be honoured by this extension. This would make it easy to for example exclude standard library modules from the analysis that would otherwise pollute the problem list if you ever jump to them.

Of course you can configure exclude paths in `pyproject.toml`, but you would have to do that for each project individually, and in cases where you edit stand-alone scripts you wouldn't even have a project file.

If both these VS Code patterns and excludes in the `pyproject.toml` are configured I would suggest using both. This means people can have their own excludes configured for a shared project, and if their normal excludes are undesirable for a specific project they can always set the patterns to a different value in their workspace settings.

**Comment by charliermarsh** [comment]
Oh interesting, I didn’t know about this setting. On the surface, I agree with you, though I’d like to see if / how other similar extensions handle them before committing.

**Comment by charliermarsh** [comment]
It looks like the other Python extensions don't respect this, but there's a recently-opened issue (https://github.com/microsoft/vscode-flake8/issues/147) discussing it.

**Comment by majutsushi** [comment]
There was some recent discussion in the pylance project about how this setting is meant for linters: https://github.com/microsoft/pylance-release/issues/4100

Here's the same feature request for the pylint extension: https://github.com/microsoft/vscode-pylint/issues/199
According to that issue the setting is honoured when using the system pylint but not when using the extension, although I'm not sure if the former is still true after the pylance change discussed above.

**Comment by cnpryer** [comment]
My 2c: I think what would be nice to see is a pattern of projects supporting it to justify the effort/payoff. But imo this does seem like a nicer way to do it than to have configuration for each extension.

I'm not familiar with how these extensions are built, but it seems like there are varying levels of support. Is the intention behind `python.linting.ignorePatterns` to have linters respect its ignore?

I also read about some other extensions utilizing the .cwd to manage in/vs out of the project. If https://github.com/charliermarsh/ruff-lsp/pull/99 works out it'd be an improvement on what's currently possilbe.

**Comment by charliermarsh** [comment]
Ok, it looks like this setting is considered legacy, and they plan to deprecate it: https://github.com/microsoft/vscode-flake8/issues/147#issuecomment-1613871609.
