### ISSUE TITLE
Ruff runs against python std library and third-party dependencies when "Go to definition" or debugging, no way to disable this

### ISSUE THREAD

**Issue by cspotcode** [astral-sh/ruff-vscode#176]
I often use a debugger or "Go to definition" when diagnosing errors.  This means I am often viewing the source of third-party dependencies or python's own standard library.

The problem is: Ruff flags pages of issues in these files, filling up the Problems pane, obscuring the issues that I actually want to see.

Here is an example of using `@property` and `functools.partial` in my code, then pressing F12 on them to view their declarations.  I chose this example because it does not require third-party dependencies, but more often this happens using something like "arcade," a complex game engine where it's very helpful to step a debugger into arcade's code.

The code is here: https://github.com/cspotcode/repros/tree/ruff-vscode

![image](https://user-images.githubusercontent.com/376504/233761754-0a88fbc7-e5c9-4b98-9721-7efe6eb21d49.png)
![image](https://user-images.githubusercontent.com/376504/233761803-256315c4-7706-4420-b3da-83ed74a654d8.png)

Python's standard library does not follow ruff's standard formatting rules, and seeing these failures is not useful for several reasons:

- I have no reason to rewrite python's standard library to fix these errors.
- Knowing that it has lines longer than 88 characters does not point me towards a problem.
- None of these diagnostics appear when running ruff from the CLI.

Stepping back a bit, I want to configure the VSCode extension to help me write my project.  This means linting my own project because I have opted-in to linting, in a way that matches the errors I'll see running ruff on CI.

**Comment by charliermarsh** [comment]
Interestingly, I think this would be solved by #175.

**Comment by cnpryer** [comment]
I wasn’t able to reproduce the pylance extension reporting ruff’s responsible for in the first pic.

VSCode:
```
Version: 1.77.3 (Universal)
OS: Darwin arm64 22.3.0
```

Ruff Extension:
```
Name: Ruff
Id: charliermarsh.ruff
Version: 2023.12.0
```

Pylance Extension:
```
Name: Pylance
Id: ms-python.vscode-pylance
Version: 2023.4.30
```

Python Extension:
```
Name: Python
Id: ms-python.python
Version: 2023.6.1
```

For the second part, what about using the settings.json file for now?

```
 "ruff.args": ["--extend-exclude", “/some/path/**/*.py"]
```

**Comment by cspotcode** [comment]
> I wasn’t able to reproduce the pylance extension reporting ruff’s responsible for in the first pic.

I'm not sure I understand, maybe my reproduction was unnecessarily confusing.  Ruff is not responsible for any of the Pylance diagnostics.  I included pylance stuff in my reproduction to show how I've been able to workaround a similar issue with a different extension.  But as far as I know, the two extensions are not influencing each other in any way.

The picture is meant to show a few useful diagnostics from both ruff and pylance -- problems I need to fix -- and how the unhelpful diagnostics are drowning them out.

> For the second part, what about using the settings.json file for now?

I don't think that's working, I tried excluding the directory containing `builtins.pyi`, and I get a new "system cannot find the file specified." error from ruff.  I suspect it's a ruff error rather than a linting diagnostic.

Here is the invocation:

```
Using interpreter executable: C:\Users\cspot\scoop\apps\python\current\Scripts\ruff.exe
Running Ruff with: ['C:\\Users\\cspot\\scoop\\apps\\python\\current\\Scripts\\ruff.exe', '--force-exclude', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--extend-exclude', 'C:/Users/cspot/.vscode/extensions/ms-python.vscode-pylance-2023.4.30/dist/typeshed-fallback/**/*.pyi', '--stdin-filename', 'c:\\Users\\cspot\\Documents\\dev\\@cspotcode\\repros\\src\\main.py']
Cancel notification for unknown message id "1"
```

Pasting that command into a terminal and running it, I get:

```
PS C:\Users\cspot\Documents\dev\@cspotcode\repros> C:\Users\cspot\scoop\apps\python\current\Scripts\ruff.exe --force-exclude --no-cache --no-fix --quiet --format json - --extend-exclude C:/Users/cspot/.vscode/extensions/ms-python.vscode-pylance-2023.4.30/dist/typeshed-fallback/**/*.pyi --stdin-filename c:\Users\cspot\Documents\dev\@cspotcode\repros\src\main.py                
[
  {
    "code": "E902",
    "message": "The system cannot find the file specified. (os error 2)",
    "fix": null,
    "location": {
      "row": 1,
      "column": 1
    },
    "end_location": {
      "row": 1,
      "column": 1
    },
    "filename": "C:\\Users\\cspot\\Documents\\dev\\@cspotcode\\repros\\-",
    "noqa_row": 1
  }
]
PS C:\Users\cspot\Documents\dev\@cspotcode\repros>   
```

It looks like the hyphen is being interpreted as a filename.

I realize that sometimes Windows shells, either PowerShell or cmd, cause weirdness with command line arg parsing, but it doesn't seem like that's the issue here.

**Comment by cnpryer** [comment]
Ah I see the confusion. I meant

> ~~I wasn’t able to reproduce the pylance extension reporting ruff’s responsible for in the first pic.~~

I wasn’t able to reproduce the ruff lints from builtins.pyi as shown in the first pic*. 

Sorry about that.

If I can find a windows laptop I'll try tinkering with this there.

**Comment by cspotcode** [comment]
> I wasn’t able to reproduce the ruff lints from builtins.pyi as shown in the first pic*.

I wonder, are you using a venv?  In my case, the `builtins.pyi` file resides in a directory that does not have a `pyproject.toml` anywhere up the directory tree to the root of my filesystem.

**Comment by cspotcode** [comment]
I see the same lints on `builtins.pyi` when running in Linux -- technically WSL2 -- so I feel like it should be happening there too.

**Comment by charliermarsh** [comment]
We probably properly ignore anything in a venv, since venv’s are excluded by default — but there’s no reason (in current code) that we’d ignore the contents of .vscode. Seems like we should though (or rather, that we should respect the VS Code linter ignore variables, which include .vscode by default IIUC).

I’m confused as to why adding that as an explicit exclusion isn’t working for you, or whatever’s going on with the way your filename is being interpreted, but I’ll have to play around with it myself to know what’s going on.

**Comment by cnpryer** [comment]
Try
```
 "ruff.args": ["--extend-exclude", "c:/Users/cspot/.vscode/**/*.pyi"]
```

I tried on a windows machine and it looks like it gets mad at C: not being c:

**Comment by cnpryer** [comment]
> I wonder, are you using a venv? In my case, the builtins.pyi file resides in a directory that does not have a pyproject.toml anywhere up the directory tree to the root of my filesystem.

No sorry, I could have clarified this as well. I was using my .pyenv installations. No venv. I'm not sure .pyenv installs are excluded by default.

**Comment by charliermarsh** [comment]
I'm looking into this, I feel like the exclusions aren't working as expected in the extension.

**Comment by charliermarsh** [comment]
There's at least one bug here with no properly respecting `--extend-exclude` in `settings.json`. Once I fix that, you should be able to do something like this in the interim:

```json
{
    "ruff.args": [
        "--extend-exclude",
        ".vscode",
        "--extend-exclude",
        "site-packages",
        "--extend-exclude",
        ".pyenv"
    ]
}
```

**Comment by charliermarsh** [comment]
I think #99 should enable users to ignore `.vscode` and such via `--extend-exclude`, as above.

**Comment by cnpryer** [comment]
So is the idea to install the project to vscode after having built it with ruff-lsp ungraded to a fresh whl? 

```
2023-04-22 21:01:33.360 [info] Successfully installed extension charliermarsh.ruff vscode-userdata:/Users/chrispryer/.vscode/extensions/extensions.json
```

**Comment by cnpryer** [comment]
If I wanted to test this.

**Comment by cnpryer** [comment]
Also is this the 99 you meant to tag? https://github.com/charliermarsh/ruff-lsp/pull/99

**Comment by charliermarsh** [comment]
@cnpryer - Yes, thanks -- updated!

To test, I often just manually copy over the source files from `ruff-lsp` into `ruff-vscode/bundled/libs/ruff_lsp` after running `just setup`. It's hacky and annoying, open to better systems for sure!
