### ISSUE TITLE
The Ruff server crashed 5 times in the last 3 minutes. [MacOS]

### ISSUE THREAD

**Issue by foucdeg** [astral-sh/ruff-vscode#182]
This warning message pops on my VSCode instance and Ruff doesn't highlight errors or autofix.

In Output > Ruff, I get: 

```
Server Command [RUN]: ./.venv/bin/ruff /Users/foucauld/.vscode/extensions/charliermarsh.ruff-2023.12.0-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: ./.venv/bin/ruff /Users/foucauld/.vscode/extensions/charliermarsh.ruff-2023.12.0-darwin-arm64/bundled/tool/_debug_server.py
[Info  - 10:53:23] Connection to server got closed. Server will restart.
[Info  - 10:53:23] Connection to server got closed. Server will restart.
[Info  - 10:53:23] Connection to server got closed. Server will restart.
[Info  - 10:53:23] Connection to server got closed. Server will restart.
[Error - 10:53:23] Connection to server got closed. Server will not be restarted.
```

Using the command `Ruff: Restart Server`, the same output is printed again.

VS Code : 1.77.3
Extension version: 2023.12.0
macOS : 13.3.1 (a) (22E772610a)

**Comment by foucdeg** [comment]
I've tried running the commands labeled `Server Command [RUN]` and `Server Command [DEBUG]` in my terminal. In both cases, no output and the return status is 0.
I've tried uninstalling and reinstalling the extension.

**Comment by foucdeg** [comment]
@charliermarsh thanks for triaging. Anything I can further investigate on my side?

**Comment by charliermarsh** [comment]
@foucdeg - Sorry for dropping the ball here. The most useful would be to see the debug logs, as described here: https://github.com/astral-sh/ruff-vscode/issues/198#issuecomment-1572819308.

**Comment by foucdeg** [comment]
@charliermarsh here's something interesting I didn't see before:

```
2023-06-29 16:43:34.905 [info] Name: Ruff
2023-06-29 16:43:34.905 [info] Module: ruff
2023-06-29 16:43:36.919 [error] Python version undefined.undefined is not supported.
2023-06-29 16:43:36.919 [error] Selected python path: undefined
2023-06-29 16:43:36.919 [error] Supported versions are 3.7 and above.
2023-06-29 16:43:37.012 [info] Server run command: ./.venv/bin/ruff /Users/foucauld/.vscode/extensions/charliermarsh.ruff-2023.30.0-darwin-arm64/bundled/
```

**Comment by foucdeg** [comment]
It seems that *not* having this setting fixes the issue 🤔 the situation must have evolved because I remember adding the setting to try and fix the issue.

**Comment by foucdeg** [comment]
Or it seems that I got mixed up between `interpreter` and `path` settings. Anyway, things are working now.
