### ISSUE TITLE
Feature request: link to rules

### ISSUE THREAD

**Issue by tekumara** [astral-sh/ruff-vscode#190]
In diagnostics, link to the relevant section of the [rules docs](https://beta.ruff.rs/docs/rules/).

**Comment by JonathanPlasse** [comment]
You can have access to the rule documentation by using
```console
ruff rule E501
```

**Comment by tekumara** [comment]
Nice, I think what I'm after in some cases is more detail, eg: for B905 

<img width="696" alt="CleanShot 2023-05-14 at 10 13 22@2x" src="https://github.com/charliermarsh/ruff-vscode/assets/125105/96433dd5-8b0d-4247-b7b1-0346934faa23">

I'm not sure why specifying the `strict` param is recommended. It would be nice to be able to jump to somewhere with the rationale.

For example, hadolint has links in the diagnostic message that take you to their wiki (eg: [DL3013](https://github.com/hadolint/hadolint/wiki/DL3013)):

<img width="743" alt="CleanShot 2023-05-14 at 10 09 34@2x" src="https://github.com/charliermarsh/ruff-vscode/assets/125105/d53fb053-751e-4f0b-90f9-2930a19f56f2">

I guess the problem is less the lack of links, and more that there isn't a good place to jump to for more info.

**Comment by charliermarsh** [comment]
ESLint and Prettier support this with a code action ("Open the documentation"). I think we should add that _and_ add these links.

**Comment by charliermarsh** [comment]
> Nice, I think what I'm after in some cases is more detail, eg: for B905...

The other problem in this case is that we haven't yet added documentation for the Bugbear rules. We're at > 60% coverage, but the Bugbear category hasn't been done yet.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/ruff-lsp/pull/163.
