### ISSUE TITLE
Aintivirus Avira report ruff.exe as Drop.Win64.MemAllocSelf on Windows 11

### ISSUE THREAD

**Issue by jackjyq** [astral-sh/ruff-vscode#196]
![image](https://github.com/astral-sh/ruff-vscode/assets/16525413/47ab8fe8-90b4-48ec-9b5f-7f9b6674314f)

I have use ruff-vscode for a few days, and yesterday (2023-05-24), the Avira report ruff.exe as Drop.Win64.MemAllocSelf on Windows 11. Is that a false alert?

**Comment by MichaReiser** [comment]
Hmmm. It's difficult to find any information about what the threat is about. The only useful information I found is that deno has the same issue https://github.com/denoland/deno/issues/5690

**Comment by jackjyq** [comment]
Unfortunately, Ariva does not give me any more detail, nor on its [website](https://www.avira.com/en/support-virus-lab?threat=Drop.Win64.MemAllocSelf)

- I have removed `ruff.exe` from Quarantine and re-scan the same file using Ariva, the result is negative. 
- I have uploaded ruff.exe to [virus total](https://www.virustotal.com/gui/file/a9111ef659d0c6aadb00ad61cec729ed0e923ee23e431d8cce13a3b039c0ffa4/detection) and the result is negative.
- According to [Ruff VSCode](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff), the extension got updated at 5/15/2023. Therefore, the issue is not triggered by an update of `ruff-vscode`


[ruff.zip](https://github.com/astral-sh/ruff-vscode/files/11561469/ruff.zip)

**Comment by charliermarsh** [comment]
Ok, I'm not sure there's much we can do here, so going to close for now. Thank you for reporting!
