### ISSUE TITLE
Quick Fix "Ruff: disable ..." often unhelpful

### ISSUE THREAD

**Issue by nsaje** [astral-sh/ruff-vscode#199]
I rarely disable errors but I often use quick fixes. There are many cases where Ruff's "disable" prompt is offered as a first option instead of a much more useful one, for example

<img width="537" alt="Screenshot 2023-06-02 at 11 08 15" src="https://github.com/astral-sh/ruff-vscode/assets/156006/282722cd-cb24-4299-9e20-f3184d824085">

Is there a way to de-prioritize this quick fix option? Alternatively, could we have an option in settings to disable either this particular option or all Ruff quick fix suggestions (I use autofix so I never need ruff's quick fixes)

Thanks!

**Comment by charliermarsh** [comment]
ESLint has a `eslint.codeAction.disableRuleComment` setting to disable these -- we should add the same.
