### ISSUE TITLE
Support for go-to definition? 

### ISSUE THREAD

**Issue by peekxc** [astral-sh/ruff-vscode#203]
Does Ruff support go-to definition (also called "jump to definition") functionality, like PyLance?

According to VS-Code's [language server extension guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), this is theoretically possible. 

> The following language features are currently supported in a language server along with code completions:
> ...
>     Goto Definition: provides go to definition support for a symbol selected in a text document.
> ... 

When I install Ruff, the things that are mentioned as part of the extension work flawlessly (linting, auto-fix imports, etc.). 

That being said, there is no "ruff" option in the Pythons "Language Server" option---it's unclear to me whether this is something that falls under the purview of ruff or VS Code to change

**Comment by zanieb** [comment]
Hey! There's discussion about this over at https://github.com/astral-sh/ruff-lsp/issues/23 — but ruff-lsp doesn't support this at this time and is intended to be used alongside a tool that does.
