### ISSUE TITLE
[BUG] Something goes wrong with pydocstyle

### ISSUE THREAD

**Issue by Andy-Dihong-Luo** [astral-sh/ruff-vscode#207]
After I update Ruff extention to 2023.18.0, it seems that something goes wrong with the pydocstyle rules. It mentions D201, D202, D205, D412, where should not be any errors in the old version. Also, when Ruff tried to auto fix my code, it messed everything up, adding strange blank lines in my code. Please fix it ASAP.
**Before**:

![image](https://github.com/astral-sh/ruff-vscode/assets/128155646/378b7d76-c53c-4a5a-906c-c50e6ea1b0f7)

**After**:

![image](https://github.com/astral-sh/ruff-vscode/assets/128155646/6c37a1cd-055c-4569-9f0a-002343522579)

**Comment by charliermarsh** [comment]
I'll take a look.

**Comment by charliermarsh** [comment]
Are you on Windows?

**Comment by charliermarsh** [comment]
(If you switch to the nightly channel, you'll revert back to the last build that was working for you. But I'm going to try and fix this now.)

**Comment by charliermarsh** [comment]
If you're able to upgrade to v2023.19.11660418 (pre-release), it'd be great to know if that solves the problem.

**Comment by charliermarsh** [comment]
I believe this is closed by https://github.com/astral-sh/ruff-vscode/pull/208 (https://github.com/astral-sh/ruff-lsp/pull/137), publishing to main channel now.
