### ISSUE TITLE
Command "Ruff: fix all auto-fixable problems" stopped working with last update

### ISSUE THREAD

**Issue by lucas-labs** [astral-sh/ruff-vscode#215]
As the title says, after updating the extension today, I noticed that the command "Ruff: fix all auto-fixable problems" stopped working. Auto fixing on save still works, but manually triggering it with the command doesn't.

Reverting back to v2023.16.0 fixes the issue.

**Comment by charliermarsh** [comment]
This is fixed in the next release, which I'll probably cut tonight.
