### ISSUE TITLE
Incorrect extension argument nukes focused file

### ISSUE THREAD

**Issue by ffolkes1911** [astral-sh/ruff-vscode#238]
Currently when adding arguments for `ruff` through `vscode` UI interface the tooltip provides an example `"args": ["--config=/path/to/pyproject.toml"]`, which is correct for the settings.json file, but not for `vscode` UI. This in itself is not a significant problem, however if we use this example in the UI for `ruff` args (which a person unfamiliar with vscode/cli args may do), the extension nukes the opened and focused file on save, file is left only containing brackets "[]". I tested a bit more and it seems that any invalid argument for the extension reproduces the nuking issue (double quote, letter 'a', dash).  

* A minimal code snippet that reproduces the bug - add any invalid argument to settings.json "ruff.args" or through UI (a, ", -). This invalid argument may have to be the first arg. Execute ruff linter. I just saved an opened file with the "run on save" feature.
* The current Ruff and VS Code settings (any relevant sections from your `pyproject.toml` and `settings.json`) - reproduced on two different projects, probably not related to `pyproject.toml`. `settings.json:  "ruff.run": "onSave", "ruff.fixAll": false, "ruff.enable": false, "ruff.args": [ "a" ]`
* The current Ruff and VS Code extension versions (`ruff --version`). - `ruff` should be `ruff==0.0.272`, vscode extension `v2023.26.0`
* A description of your environment (e.g., operating system, Python version, etc.). - Ubuntu 20.04.06 LTS, python3.10.12

**Comment by SparksFlyx3** [comment]
Also happened to me! Very surprising & inconvenient.

**Comment by charliermarsh** [comment]
I'll take a look at this today, sorry about that!

**Comment by charliermarsh** [comment]
This will be fixed in the next Ruff release (it requires a change in Ruff). Thanks for bringing it to my attention.

**Comment by charliermarsh** [comment]
(Closing as this'll be fixed in the next release. Thanks!)
