### ISSUE TITLE
Add a fix formatter

### ISSUE THREAD

**Issue by interrrp** [astral-sh/ruff-vscode#241]
It would be neat if you could set Ruff as a Python formatter running `ruff --fix` to format. Currently, this is not possible:
![image](https://github.com/astral-sh/ruff-vscode/assets/111111938/ec0bd38a-783a-4a9e-b41a-f3201f48f5a1)

**Comment by zanieb** [comment]
I think we're most likely to do this as part of https://github.com/astral-sh/ruff/issues/1904 — performing actual formatting instead of applying fixes via code actions.
