### ISSUE TITLE
Setting a custom project.toml file

### ISSUE THREAD

**Issue by carrickkv2** [astral-sh/ruff-vscode#245]
So I've looked at the extension settings, and it says to add additional arguments we should do something like this
"args": ["--config=/path/to/pyproject.toml"]

I've done that by setting something like this. 
"G:\projects_python_only\PROJECTS\pyproject.toml"

Unfortunately, ruff is telling me it can't find the file. When I try to save, I get the error below. 
Note that the file I'm trying to save is in the location below. File names have been redacted for privacy. 
Location: g:\\projects_python_only\\PROJECTS\\Python\\Work\\*****\\s*****\\****

Full error:
[
    {
        "code": "E902",
        "end_location": {"column": 1, "row": 1},
        "filename": 'g:\\projects_python_only\\PROJECTS\\Python\\Work\\******\\s*******\\****\\"G:\\projects_python_only\\PROJECTS\\pyproject.toml"',
        "fix": null,
        "location": {"column": 1, "row": 1},
        "message": "The filename, directory name, or volume label syntax is incorrect. (os error 123)",
        "noqa_row": 1,
        "url": null,
    },
    {
        "code": "E902",
        "end_location": {"column": 1, "row": 1},
        "filename": "g:\\projects_python_only\\PROJECTS\\Python\\Work\\*****\\*****\\*****\\-",
        "fix": null,
        "location": {"column": 1, "row": 1},
        "message": "The system cannot find the file specified. (os error 2)",
        "noqa_row": 1,
        "url": null,
    },
]

From the error above it looks like the location I gave as an arg is being appended to the location where the file is supposed to be.
I don't know if I'm doing anything wrong and would like some help. 

Thank you

**Comment by charliermarsh** [comment]
Do you mind sharing your full `settings.json`, or at least the Ruff portion?

**Comment by carrickkv2** [comment]
> Do you mind sharing your full `settings.json`, or at least the Ruff portion?

Here is the ruff section, if you still need the full one please let me know


// Additional command-line arguments to pass to `ruff`, e.g., `"args": ["--config=/path/to/pyproject.toml"]`. Supports a subset of Ruff's command-line arguments, ignoring those that are required to operate the LSP, like `--force-exclude` and `--verbose`.
	"ruff.args": [],

	// Whether to display Quick Fix actions to disable rules via `noqa` suppression comments.
	"ruff.codeAction.disableRuleComment": {
		"enable": true
	},

	// Whether to display Quick Fix actions to autofix violations.
	"ruff.codeAction.fixViolation": {
		"enable": true
	},

	// Whether to enable the Ruff extension.
	"ruff.enable": true,

	// Whether to register Ruff as capable of handling `source.fixAll` actions.
	"ruff.fixAll": true,

	// Strategy for loading the `ruff` executable. `fromEnvironment` picks up Ruff from the environment, falling back to the bundled version if needed. `useBundled` uses the version bundled with the extension.
	//  - fromEnvironment: Use `ruff` from environment, falling back to the bundled version if `ruff` is not found.
	//  - useBundled: Always use the bundled version of `ruff`.
	"ruff.importStrategy": "fromEnvironment",

	// Path to a Python interpreter to use to run the linter server.
	"ruff.interpreter": [],

	// Whether to register Ruff as capable of handling `source.organizeImports` actions.
	"ruff.organizeImports": true,

	// Path to a custom `ruff` executable, e.g., `["/path/to/ruff"]`.
	"ruff.path": [],

	// Run Ruff on every keystroke (`onType`) or on save (`onSave`).
	//  - onType: Run Ruff on every keystroke.
	//  - onSave: Run Ruff on save.
	"ruff.run": "onType",

	// Controls when notifications are shown by this extension.
	//  - off: All notifications are turned off, any errors or warning are still available in the logs.
	//  - onError: Notifications are shown only in the case of an error.
	//  - onWarning: Notifications are shown for errors and warnings.
	//  - always: Notifications are show for anything that the server chooses to show.
	"ruff.showNotifications": "off",

	// Traces the communication between VSCode and the ruff-lsp.
	"ruff.trace.server": "off",

**Comment by charliermarsh** [comment]
Thanks! It looks like `"ruff.args"` is empty above -- did you intend to include the path you mentioned in the initial comment?

**Comment by carrickkv2** [comment]
Yes, I did. Seems like VS code is not updating the JSON. Updating it manually to see the effect.

**Comment by charliermarsh** [comment]
Did you include the `--config=` prefix when setting `args`? The error looks like Ruff is trying to lint your configuration file.

**Comment by carrickkv2** [comment]
Below is exactly what I wrote.
"args": ["--config="G:\projects_python_only\PROJECTS\pyproject.toml"]

**Comment by advait404** [comment]
Hi, I am having the same issue. I can't get ruff to work with a custom path for project.toml.

**Comment by advait404** [comment]
I was able to make it work. I think you may need to use "/" instead of "\\" in the path. below is my setting.json
optionally, you can save the configurations directly in the setting file through the CLI arguments.

```
  "ruff.args": [
    // "--select=ALL",
    // "--ignore=ERA001,E501",
    "--config=D:/Portable Apps/VSCodium/data/pyproject.toml",
  ],
```
