### ISSUE TITLE
[Feature Request] Panel with all ruff warnings

### ISSUE THREAD

**Issue by george-gca** [astral-sh/ruff-vscode#246]
It would be nice to have a new vscode panel displaying only the problems identified by ruff, much like [TODO Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree), so it would be easier to navigate directly to the lines pointed by ruff.

Maybe even grouping them by the ruff code, like display for a file all the warnings, having a group for all specific codes like [f-string missing placeholders](https://beta.ruff.rs/docs/rules/f-string-missing-placeholders/). This way would be much faster to identify and solve first the easier ones.

Leaving the example image from the extension here as reference:

![image](https://github.com/astral-sh/ruff-vscode/assets/31376482/ed83e159-ebe8-41fa-87f1-6cca00f843e8)

**Comment by bigluck** [comment]
I'd love to see the errors of all the project files on the build-in "Problems" panel.

Now it works only when you have a file opened, but other extensions (https://github.com/matangover/mypy-vscode) show all the errors from all the files.

**Comment by JPMarais-Inscorep** [comment]
This would be very useful, especially if you no longer have ruff installed in your venv as you are using the bundled version and thus do not have access to the ruff cli to check the whole project.

**Comment by zanieb** [comment]
@bigluck see https://github.com/astral-sh/ruff-vscode/issues/145
