### ISSUE TITLE
No `SyntaxError` if commas missing in List

### ISSUE THREAD

**Issue by stevenlis** [astral-sh/ruff-vscode#253]
```
ruff - v2023.32.0
```
```
Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:40:17.963Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

```
name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - numpy=1.22.*
  - scipy
  - jupyter
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - lxml
  - openpyxl
  - tabulate
  - geopandas=0.12.*
  - nbconvert
  - pandera=0.13.*
  - statsmodels=0.13.*
  - pyarrow=11.0.0
  - polars=0.18.5
  - altair>=5.0.0
  - pandas=2.0.2
  - xlsx2csv
  - requests=2.31.*
  - pip
  - pip:
    - vl-convert-python==0.9.0
    - ydata-profiling==4.3.0
```

For some reason, unlike in a dict, I'm not getting a `SyntaxError` in a list if commas are missing between each item.

<img width="225" alt="CS-Gveb7bYv@2x" src="https://github.com/astral-sh/ruff-vscode/assets/33796896/342d93e9-01ab-4d1b-be28-76a46c90e9c8">

<img width="614" alt="CS-rt1OWkZv@2x" src="https://github.com/astral-sh/ruff-vscode/assets/33796896/311bc2c4-558a-4f7d-99b3-a605b403bfc3">

Am I missing something?

**Comment by zanieb** [comment]
Hey @stevenlis you don't get an error with your list example because you've accidentally created a multiline string

```
In [1]: x = [
   ...:      'a'
   ...:      'b'
   ...:      'c'
   ...: ]

In [2]: print(x)
['abc']
```

If you were to use numbers, you'd get an error

```
In [3]: x = [
   ...:     1
   ...:     2
   ...:     3
   ...: ]
  Cell In [3], line 2
    1
    ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Comment by stevenlis** [comment]
@zanieb Oh I see. Thanks for pointing this out. Is there any way we could have ruff supports this on strings as well? Maybe add a toggle for it?

**Comment by stevenlis** [comment]
@zanieb Sorry. It's still not clear to me how do I enable this so that I will get a warning for the following code. Do I do this in `"ruff.args"`?

```
In [1]: x = [
   ...:      'a'
   ...:      'b'
   ...:      'c'
   ...: ]
```
