### ISSUE TITLE
Run ruff on both `onType` and `onSave`?

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff-vscode#254]
Is it possible to extend the `ruff.run` setting to run ruff on both `onType` and `onSave`?

**Comment by harupy** [comment]
`onSave` is useful when rerunning ruff after adding or removing rules in `pyproject.toml`

**Comment by charliermarsh** [comment]
Hm, perhaps `onType` should imply `onSave` too.

**Comment by harupy** [comment]
https://github.com/microsoft/vscode-eslint/issues/885

`onTypeOrSave`?

**Comment by charliermarsh** [comment]
I believe they're now both respected.
