### ISSUE TITLE
Support for Jupyter Notebooks

### ISSUE THREAD

**Issue by advait404** [astral-sh/ruff-vscode#256]
Hi, currently the extension does not perform linting for jupyter notebooks. I have tried adding "include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]" into the pyproject.toml but it still fails to work.

- running on windows 10
-  latest extension version
- VScodium version 1.79.2

setting.json
```
  "ruff.args": [
    "--config=D:/Portable Apps/VSCodium/data/pyproject.toml",
  ],
```

pyproject.toml
```
[tool.ruff]
select = ["ALL"]
ignore = ["ERA001","E501"]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
```

**Comment by charliermarsh** [comment]
@dhruvmanila - Do you know if Jupyter linting is enable-able in the current version of the extension? (I can also test this tomorrow.)

**Comment by charliermarsh** [comment]
@advait404 - Do you mind also confirming your Ruff version? Are you using the version that ships with the extension, or do you have Ruff installed in your environment?

**Comment by advait404** [comment]
I am using the ruff version bundled with the extension. Extension version is 2023.32.0

**Comment by dhruvmanila** [comment]
No, Jupyter Notebook in VSCode isn't supported yet. I think it'll require some changes in `ruff-lsp` to support it. I'll look into it - me and @konstin discussed this briefly on Discord.

**Comment by markeyser** [comment]
Please, fix this issue; we will move to Ruff in my 80-people AI team in the coming weeks. We use VS Code notebooks as much as Python scripts.

**Comment by blakeNaccarato** [comment]
Your team may already be aware of this, but in addition to completion of https://github.com/openlawlibrary/pygls/pull/356, the VSCode September 2023 release [finalizes the notebook Code Action API](https://github.com/openlawlibrary/pygls/pull/356) and includes the [`Notebook CodeActionKind`](https://code.visualstudio.com/api/references/vscode-api#CodeActionKind). This results in `notebook.source.`-prefixed actions which have the full-notebook scope. This may be relevant to your implementation here, along with whatever changes may be needed in `ruff-lsp`.

**Comment by dhruvmanila** [comment]
Interesting, thanks for letting us know! I was not aware of this. I'll give it a detailed look later but I don't think this is useful to us as our extension is based on `ruff-lsp` which is based on the LSP protocol. And IIUC, this is specific to the VSCode extension.
