### ISSUE TITLE
Show config doc on hover in `pyproject.toml`

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff-vscode#262]
https://github.com/astral-sh/ruff-vscode/assets/17039389/535b5cc2-caa9-4d1d-bd23-5d034268c208

Not an issue, but a feature request. Is this useful?

**Comment by zanieb** [comment]
Seems useful. How is it implemented?

**Comment by harupy** [comment]
The ruff-lsp code looks like this:

```diff
diff --git a/ruff_lsp/server.py b/ruff_lsp/server.py
index c583fe8..2993274 100755
@@ -329,6 +332,9 @@ CODE_REGEX = re.compile(r"[A-Z]+[0-9]+")
 @LSP_SERVER.feature(TEXT_DOCUMENT_HOVER)
 async def hover(params: HoverParams) -> Hover | None:
     """LSP handler for textDocument/hover request."""
+    if params.text_document.uri.endswith("pyproject.toml"):
+        return await hover_toml(params)
+
     document = LSP_SERVER.workspace.get_document(params.text_document.uri)
     match = NOQA_REGEX.search(document.lines[params.position.line])
     if not match:
@@ -359,6 +365,142 @@ async def hover(params: HoverParams) -> Hover | None:
     return None
 
 
+OPTION_REGEX = re.compile(r"^([a-z-_]+)\s*=\s*")
+
+
+async def hover_toml(params: HoverParams) -> Hover | None:
+    """LSP handler for textDocument/hover request."""
+    document = LSP_SERVER.workspace.get_document(params.text_document.uri)
+    for line in reversed(document.lines[: params.position.line]):
+        if line.startswith("[tool.ruff"):
+            break
+        elif line.startswith("["):
+            return
+    else:
+        return
+
+    line = document.lines[params.position.line]
+    if m := OPTION_REGEX.search(line):
+        option = m.group(1)
+        result = await _run_subcommand_on_document(document, args=["config", option])
+        if result.stdout:
+            return Hover(
+                contents=MarkupContent(
+                    kind=MarkupKind.Markdown,
+                    value=result.stdout.decode("utf-8").strip(),
+                )
+            )
+
+    return None
```

**Comment by zanieb** [comment]
I love it. Can we support the `ruff.toml` file as well? Should probably make sure @charliermarsh is on board too.

**Comment by harupy** [comment]
> Can we support the ruff.toml file as well?

Yes, a piece of 🍰

**Comment by charliermarsh** [comment]
This looks really nice. My only question is how it interacts with the JSON schema and extensions that leverage it. In other words, is it possible for us to instead get this for free via our JSON schema? I get _just_ the description on-hover, and it doesn't seem to work for all settings for reasons I don't understand.

<img width="575" alt="Screen Shot 2023-08-08 at 10 20 19 AM" src="https://github.com/astral-sh/ruff-vscode/assets/1309177/9b33ffaf-0a05-4b42-8fac-e4de819e5b72">

**Comment by harupy** [comment]
> is it possible for us to instead get this for free via our JSON schema?

The JSON schema is a map that maps a setting name to its description. It should work.

> I get just the description on-hover.

Is this because the JSON schema only contains description?

> it doesn't seem to work for all settings for reasons I don't understand.

which settings don't work?
