### ISSUE TITLE
Is there a way to change the severity?

### ISSUE THREAD

**Issue by mistalaba** [astral-sh/ruff-vscode#264]
Basically, I feel warnings aren't enough, I would love to be able to have Ruff report issues as errors to be more in your face like pylint and flake8.
Thank you!

**Comment by zanieb** [comment]
Sorry we don't support this yet.

Related discussion at https://github.com/astral-sh/ruff-vscode/issues/161

**Comment by mistalaba** [comment]
Ok, thanks for the reply 🙏
