### ISSUE TITLE
Ruff VScode --fix setting ignore

### ISSUE THREAD

**Issue by alexlatif** [astral-sh/ruff-vscode#269]
Hello @charliermarsh, thank you for your work.

I have been looping back and forth to get VScode to format with Ruff on save. Prelims:

- Python 3.11
- Mac M2
- Ruff extension v2023.34.0
- Ruff version 0.0.286

workspace settings.json
```
  "[python]": {
      "editor.defaultFormatter": "charliermarsh.ruff",
      "editor.formatOnSave": true,
      "editor.formatOnPaste": false
  },
  
 "ruff.args": ["--fix", "--line-length=88"],
```

On the Ruff output

```
Running Ruff with: /Users/../ml/.venv/bin/ruff ['--force-exclude', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--line-length=88', '--stdin-filename', '/Users/alessandrolatif/ml/src/utils/graphing.py']
```

a few lines above it says

```
2023-08-28 06:15:59.164 [info] Ignoring unsupported argument: --fix
```

but a) --line-length=88 is interpreted b) if i purposely mistype it it actually tells me there is an option of --fix

<img width="1150" alt="Screenshot 2023-08-28 at 6 15 46 AM" src="https://github.com/astral-sh/ruff-vscode/assets/25416855/e66558e5-174e-4246-bfb0-6d12fead792d">

what is going on for my workspace settings to not override the default behaviour? where are the default settings even specified?

i'm assuming as it is running from my ./venv that it is configured in .toml, but that too is a very vanilla setup

<img width="691" alt="Screenshot 2023-08-28 at 6 24 33 AM" src="https://github.com/astral-sh/ruff-vscode/assets/25416855/4a950a51-addf-45dc-b9ca-65786ae1b352">

all documentation on Ruff is helpful besides VScode setup, its not been very straightforward.

thank you in advance for your support.

**Comment by alexlatif** [comment]
The top level thing I am trying to solve is for Ruff to format on save

**Comment by charliermarsh** [comment]
Have you tried something like this?

```toml
{
  "[python]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll": true
    }
  },
  "python.formatting.provider": "black"
}
```

**Comment by alexlatif** [comment]
Partially solved in that it is not yet formatting but --fix is now a flag but it also has --no-fix

I am not sure where these flags are originating from 

2023-08-28 10:51:22.347 [info] Running Ruff with: /Users/.../.venv/bin/ruff ['--force-exclude', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--fix', '--line-length=88', '--stdin-filename', '/Users/.../src/utils/graphing.py']

**Comment by charliermarsh** [comment]
That's fine, `--fix` overrides `--no-fix`. How are you evaluating whether your configuration is working or not?

**Comment by alexlatif** [comment]
I am using the terminal output of Ruff with the above output.

I have line length set in both pyproject and settings as 88 and I am not able to get it fix this.

Though this is something that also does not seem to work if I manually Ruff a file.

Is there anything I am doing wrong to get the line length fix? Or must I also use black for this still?

**Comment by alexlatif** [comment]
Understood. Looking forward to it. Thank you.
