### ISSUE TITLE
TCH003 autofix doesn't seem to work

### ISSUE THREAD

**Issue by simkimsia** [astral-sh/ruff-vscode#284]
Same example from https://docs.astral.sh/ruff/rules/typing-only-standard-library-import/

```python
from __future__ import annotations

from pathlib import Path


def func(path: Path) -> str:
    return str(path)
```

### settings.json

```
{
  {
    "[python]": {
      "editor.defaultFormatter": "ms-python.black-formatter",
      "editor.formatOnSave": true,
      "editor.codeActionsOnSave": {
        "source.fixAll": "always",
      }
    },
    "ruff.args": ["--select=E,W,F,I001,PL,TCH", "--ignore=E203", "--per-file-ignores=**/__init__.py:F401"]
}
}
```

ruff --version -> ruff 0.0.276

### vscode

Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T06:00:27.244Z (6 days ago)
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

Python 3.11.5

### i can confirm that ruff autofix is working

when i tried the example for F401

**Comment by charliermarsh** [comment]
I just confirmed when running from the command-line (`ruff check /path/to/file.py --isolated --select TCH --fix`):

```python
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path


def func(path: Path) -> str:
    return str(path)
```

**Comment by charliermarsh** [comment]
Did you use this exact snippet in your editor? What happens when you test on the command-line?

**Comment by simkimsia** [comment]
sorry my bad, the settings.json was wrongly formatted.

Case closed.

**Comment by charliermarsh** [comment]
No worries! Thanks for following up.
