### ISSUE TITLE
option to run `ruff format` on save

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff-vscode#288]

**Comment by konstin** [comment]
That works, it's called "Editor: Format on Save Mode"

![image](https://github.com/astral-sh/ruff-vscode/assets/6826232/f2708957-b18d-40fb-bdf3-aa08b2d6ac4d)

**Comment by DetachHead** [comment]
@konstin that setting doesn't seem to work for ruff. i also tried setting the default formatter to ruff but that didn't seem to do anything either

![image](https://github.com/astral-sh/ruff-vscode/assets/57028336/4ea1e6d7-b4f5-44fe-965a-9ef1c25a61f1)

**Comment by DetachHead** [comment]
oh, turns out i haver to enable `ruff.enableExperimentalFormatter`, which is only available in user settings but not workspace settings for some reason

**Comment by konstin** [comment]
thanks for filing the second issue!
