### ISSUE TITLE
Can't format with VSCode extension using experimental formatter

### ISSUE THREAD

**Issue by abaenaDSET** [astral-sh/ruff-vscode#291]
I paste below the log from the Ruff VSCode OUTPUT:
```log
2023-09-28 12:31:26.411 [info] Running Ruff with: /home/username/project/.venv/bin/ruff ['format', '--force-exclude', '--quiet', '--stdin-filename', '/home/username/project/tests/helpers/utils.py']
2023-09-28 12:31:26.417 [info] error: unexpected argument '--force-exclude' found

  tip: to pass '--force-exclude' as a value, use '-- --force-exclude'

Usage: ruff format [OPTIONS] [FILES]...

For more information, try '--help'.
```
When you use the option `Format Document` the VSCode extension always use as args `--force-exclude` wich is not supported by the `ruff format` command.

I tried also with the Pre-release of the extension and the error remains. And also tried to override the ruff.args option in my settings.json, but the option is added at the beginning by default (before the ruff.args array)

Thanks for the extension!

Adrián

**Comment by abaenaDSET** [comment]
It was a problem with the CLI executable. It was a previous version, and it was using it from the .venv that wasn't updated.

**Comment by MichaReiser** [comment]
Sorry for the confusion that it caused. We plan to add a warning in one of the upcoming releases if the ruff version doesn't support formatting https://github.com/astral-sh/ruff/issues/7408

**Comment by ScallyGames** [comment]
I am running into this issue with ruff version 0.7.3. Is this still the same problem? If so, how can I fix it?

**Comment by dhruvmanila** [comment]
@ScallyGames I don't think this should be a problem anymore. Do you mind opening a new issue with describing what's happening and a way for us to reproduce?
