### ISSUE TITLE
fixAll on save is not respecting pyproject.toml configurations

### ISSUE THREAD

**Issue by LKajan** [astral-sh/ruff-vscode#307]
I have set VS Code to fix all issues on save. I have also set rule `F401` as unfixable in `pyproject.toml`. Regardless of the unfixable setting unused imports are cleaned from the python files on save.

If Ruff is run manually then unfixable setting is used and the unused import is not fixes as desired.
```shell
C:\Users\lauri\.vscode\extensions\charliermarsh.ruff-2023.42.0-win32-x64\bundled\libs\bin\ruff.exe .\file.py --fix              13:19:49  
file.py:1:8: F401 `re` imported but unused
Found 1 error.
```

I think I'm just missing something here?

Here's a sample project content:
```
./
|- .vscode/
|  |- settings.json
|- file.py
|- pyproject.toml
```

**file.py**
```python
import re


if __name__ == "__main__":
    print("foo")
```

**pyproject.toml**
```toml
[tool.ruff]
fixable=["ALL"]
unfixable = ["F401"]
```

**settings.json**
```json
{
    "editor.formatOnSave": true,
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
            "source.fixAll": true,
        }
    }
}
```

Ruff extension: v2023.42.0
Ruff version: ruff 0.1.0
Python: 3.10.8
OS: Windows 11 22H2

**Comment by charliermarsh** [comment]
Unfortunately I'm unable to reproduce -- I'm seeing the correct behavior locally (the import is left as-is; if I remove the `unfixable = ["F401"]`, it's removed as expected).

**Comment by LKajan** [comment]
Thank you for looking into this!

I found the culprit. Apparently I had once set and forgot the following in my user settings:
```json
"python.analysis.fixAll": [
    "source.unusedImports"
]
```
When removed everything worked as expected.

I'm sorry for the trouble. I should have tested earlier with a clean profile.

**Comment by charliermarsh** [comment]
Oh no worries! I’m just glad we were able to resolve.
