### ISSUE TITLE
How to use `ruff format` on autoSave?

### ISSUE THREAD

**Issue by niccolomineo** [astral-sh/ruff-vscode#311]
My VSCode editor is currently configured as follows:

```json
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.organizeImports": true
        },
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.formatOnPaste": false,
        "editor.formatOnType": true
    },
```

How should this be changed to have `ruff format` kick in instead of Black?

I am using `charliemarsh.ruff` instead of `ms-python.black-formatter`, but VSCode keeps on reporting it's using autopep8.

Thank you.

**Comment by charliermarsh** [comment]
It looks like you have `"editor.defaultFormatter"` in there twice. Can you try removing them both, and replacing with:

```json
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.organizeImports": true
        },
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.formatOnPaste": false,
        "editor.formatOnType": true
    },
```

Also, can you confirm you're on the latest version, which went out today?

If it still isn't working, let me know and we'll figure it out :)

**Comment by niccolomineo** [comment]
Sorry about that, I copy-pasted it wrong on here. Yes, I am on the latest version.

**Comment by niccolomineo** [comment]
Okay as I am working inside a container by means of the VSCode's extension, I just needed to restart the container (which reopens the window as well). It appears not to be using autopep8 anymore.
