### ISSUE TITLE
VS Code deprecates boolean values in `"editor.codeActionsOnSave"`

### ISSUE THREAD

**Issue by thernstig** [astral-sh/ruff-vscode#313]
The README.md shows:

```json
{
  "[python]": {
    "editor.codeActionsOnSave": {
      "source.fixAll": true
    }
  }
}
```

However `true` has been deprecated in favor of a string that should be `"always"`.

The same goes:
- `"source.organizeImports"`
- `"source.fixAll.ruff"`

**Comment by charliermarsh** [comment]
Are you able to link to the docs for this? Having trouble finding it in the spec.

**Comment by MichaReiser** [comment]
Not sure where it is in the docs but Rome supports `source.fixAll.rome` too.

**Comment by charliermarsh** [comment]
Just to clarify, I was asking about the use of a string `"always"` in lieu of a bool.

**Comment by thernstig** [comment]
@charliermarsh it was changed maybe one or two releases ago:

![image](https://github.com/astral-sh/ruff-vscode/assets/30827238/7ff448cf-b0f0-49e4-bab4-2f8218c29545)

Check the auto completion in VS Code.

A search in the VS Code repo gives: https://github.com/microsoft/vscode/pull/194345

**Comment by charliermarsh** [comment]
Very interesting, thank you so much for the links!

**Comment by thernstig** [comment]
> Not sure where it is in the docs but Rome supports `source.fixAll.rome` too.

This is something you document, see here https://github.com/astral-sh/ruff-vscode under:

> If you'd like to run Ruff on-save, but avoid allowing other extensions to run on-save, you can use Ruff's scoped source.fixAll and source.organizeImports actions via the following settings.json:

**Comment by thernstig** [comment]
It is now even in the VS Code release notes: https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto

**Comment by dhruvmanila** [comment]
Marking this as resolved as it's just a documentation update.
