### ISSUE TITLE
Support formatting jupyter notebook cells

### ISSUE THREAD

**Issue by guyrosin** [astral-sh/ruff-vscode#314]
The `Format Cell` action does nothing when the default formatter is set to ruff. The Black formatter does support this action.

This is related to #51 and probably requires https://github.com/astral-sh/ruff-lsp/pull/264.
I'm using ruff v0.1.2 and ruff-vscode v2023.44.0.

**Comment by dhruvmanila** [comment]
That's correct. Currently, we skip formatting Notebook: https://github.com/astral-sh/ruff-lsp/blob/54768646b89b276380e0898f41115d2d6c22803a/ruff_lsp/server.py#L1197-L1199. It requires the linked PR.

I'll need to look at where does the `Format Cell` action comes from i.e., do we define it in our extension or is it defined in the Python extension and then which LSP capability is being utilized there (most likely `textDocument/formatting`).

**Comment by mpearce-bain** [comment]
@dhruvmanila I see that the issue and associated PR (https://github.com/astral-sh/ruff-lsp/pull/264) are closed, but I'm still observing this behaviour. I imagine this could be user error, but wanted to confirm.

Using ruff v0.1.5 and ruff-vscode v2023.44.0 for reference. 😊

**Comment by charliermarsh** [comment]
@mpearce-bain - We haven't cut the release yet! Should be out soon.

**Comment by mpearce-bain** [comment]
I am just being a keener it seems 😂 Let me take the time to say thank you for such an awesome & performant tool then! Can't wait for the next release.

**Comment by dhruvmanila** [comment]
@mpearce-bain It's out! (https://astral.sh/blog/ruff-v0.1.5). Charlie is as fast as Ruff ;)
