### ISSUE TITLE
(Enhancement) Allow Import organization during Code Formatting

### ISSUE THREAD

**Issue by vasudev-gm** [astral-sh/ruff-vscode#315]
Not a bug maybe enhancement in future. 
Allow import organization upon running code formatting while saving the file. I wanted to disable or remove Black/isort vscode extensions and run ruff which is not resource intensive when you have multiple instances of Vscode open, say 4-5 at minimum. 

Vscode Env:
`Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
Ruff-vscode:v2023.44.0`

**Comment by vasudev-gm** [comment]
Just added code actions upon saving the file to organize imports under .vscode/settings.json:
`"editor.codeActionsOnSave": {
        "source.organizeImports": "always",
    },`
In case isort is buggy and returns "No organize import action found" when running Organize Import via Command Pallette (Ctrl + Shift + P) or Shortcut Keystroke (Shift + Alt + O). After adding above setting it should organize import upon saving

**Comment by MichaReiser** [comment]
Thanks for documenting your solution and the kind words. 

What your documented is our recommended workflow in VS Code.
