### ISSUE TITLE
When running inside dev-container based on Alpine version gets down to v2022.0.6

### ISSUE THREAD

**Issue by smsteel** [astral-sh/ruff-vscode#316]
Some dependency is missing?
Image used for dev-container has `gcompat` installed as well as Python 3.11 + ruff 0.0.287

**Comment by cemrehancavdar** [comment]
I have same issue here. Also ruff server keeps crashing.

**Comment by zanieb** [comment]
Mysterious. We'd appreciate any more information on the blocking dependency! It's weird that one of you has 0.0.108 and the other 0.0.287, @cemrehancavdar it seems likely you can upgrade?

**Comment by cemrehancavdar** [comment]
No, latest version of ruff i can download is v2022.0.6. And extension description on that version says 
`The extension ships with ruff==0.0.108.`

Even tought by pip (poetry) i can use whatever version ruff i want.

<img width="633" alt="resim" src="https://github.com/astral-sh/ruff-vscode/assets/50503448/217e77a4-35be-4fbd-bc9d-5e0cf148fa17">

**Comment by cemrehancavdar** [comment]
These are dockerfile and devcontainer configuration files that i use to create my devcontainer environment.

[devcontainer.json](https://github.com/astral-sh/ruff-vscode/files/13228943/devcontainer.json)
[dev.Dockerfile.txt](https://github.com/astral-sh/ruff-vscode/files/13228949/dev.Dockerfile.txt)

**Comment by MichaReiser** [comment]
I wonder if it is because of the included pre-built ruff binary:

https://code.visualstudio.com/api/advanced-topics/remote-extensions#supporting-nonx8664-hosts-or-alpine-linux-containers

**Comment by MichaReiser** [comment]
Looking at what changed in our extension after v2022.0.6. 

https://github.com/astral-sh/ruff-vscode/compare/2022.0.5...2022.0.9

Maybe we just need to publish an alpine linux extension which @charliermarsh published before

**Comment by MichaReiser** [comment]
Looking at https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions and at our Release workflow

https://github.com/astral-sh/ruff-vscode/blob/9b1f9cda6bec1847000312e026db6ecc6def111f/.github/workflows/release.yaml#L48-L70

We miss `alpine-x64`, `alpine-arm64` and `web`. Supporting `web` is more involved (requires WASM?) but it should be possible to add support for alpine linux if we can figure out cross compilation (@konstin ?)

**Comment by charliermarsh** [comment]
Interesting, that makes sense to me. I'd probably look at how rust-analyzer ships for alpine? https://github.com/rust-lang/rust-analyzer/blob/99e94d2938a743f8f48c6b729de4c517eeced99d/.github/workflows/release.yaml#L141

**Comment by konstin** [comment]
Cross compiling for alpine is easy, it's just `rustup target add x86_64-unknown-linux-musl` and `cargo build --target x86_64-unknown-linux-musl`, maybe you need `musl-tools` too to get the right gcc.

**Comment by MichaReiser** [comment]
> Cross compiling for alpine is easy, it's just `rustup target add x86_64-unknown-linux-musl` and `cargo build --target x86_64-unknown-linux-musl`, maybe you need `musl-tools` too to get the right gcc.

I wonder if we'll run into the same issue as documented here https://github.com/rome/tools/issues/3549

**Comment by nicocanali** [comment]
I'm running into a similar issue: I am using `"image": "mcr.microsoft.com/devcontainers/universal:2"` in a Github codespace. In my devcontainer.json I have

```
"vscode": {
      "extensions": [
        ...
        "charliermarsh.ruff"
      ]
    }
  },
```

and whenever the codespace is created, I get an older version, prompting me to update, and nothing is working:

![Image](https://github.com/astral-sh/ruff-vscode/assets/5569767/fa093b58-38db-4abf-89ee-d6296fe6ace2)

After I manually update it, everything is fine.

I tried manually specifying a version like `charliermarsh.ruff@2023.50.0`, and the logs clearly mention it:

```
2023-12-02 09:42:18.404 [info] Falling back to bundled executable: /home/codespace/.vscode-remote/extensions/charliermarsh.ruff-2023.50.0-linux-x64/bundled/libs/bin/ruff
2023-12-02 09:42:18.407 [info] [Trace - 9:42:18 AM] Received notification 'window/logMessage'.
2023-12-02 09:42:18.407 [info] Inferred version 0.1.5 for: /home/codespace/.vscode-remote/extensions/charliermarsh.ruff-2023.50.0-linux-x64/bundled/libs/bin/ruff
```

but still, the older version ends up getting installed.

**Comment by h-muhammad-ali** [comment]
Hey everyone, any updates on the fixes here? I've bumped into the same issue, can't find a solution anywhere?

**Comment by diceroll123** [comment]
Made a PR to add 3 more architectures, https://github.com/astral-sh/ruff-vscode/pull/385

🤔 it seems to build the images correctly, but I don't know how to test them locally, really 😅 skill issue on my part

**Comment by charliermarsh** [comment]
Fixed with the most recent release!
