### ISSUE TITLE
Bug: A file is reformatted via VS Code but not via CLI

### ISSUE THREAD

**Issue by thernstig** [astral-sh/ruff-vscode#318]
The following does nothing:

```
ruff format tests/utils/mongo.py
```

But saving the same file in VS Code does. (It removes a line break between some import statements).

**Output from VS Code Ruff:**

```sh
2023-10-27 10:40:32.583 [info] Using interpreter executable: /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.583 [info] Found ruff 0.1.2 at /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.583 [info] Running Ruff with: /home/userA/code/foo/.venv/bin/ruff ['--force-exclude', '--no-cache', '--no-fix', '--quiet', '--output-format', 'json', '-', '--fix', '--stdin-filename', '/home/userA/code/foo/tests/utils/mongo.py']
2023-10-27 10:40:32.588 [info] []
2023-10-27 10:40:32.616 [info] Using interpreter executable: /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.617 [info] Found ruff 0.1.2 at /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.617 [info] Running Ruff with: /home/userA/code/foo/.venv/bin/ruff ['--force-exclude', '--no-cache', '--no-fix', '--quiet', '--output-format', 'json', '-', '--fix', '--extend-ignore', 'ALL', '--extend-select', 'I001', '--stdin-filename', '/home/userA/code/foo/tests/utils/mongo.py']
2023-10-27 10:40:32.626 [info] []
2023-10-27 10:40:32.693 [info] Using interpreter executable: /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.693 [info] Found ruff 0.1.2 at /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.693 [info] Running Ruff with: /home/userA/code/foo/.venv/bin/ruff ['--force-exclude', '--no-cache', '--no-fix', '--quiet', '--output-format', 'json', '-', '--stdin-filename', '/home/userA/code/foo/tests/utils/mongo.py']
2023-10-27 10:40:32.699 [info] Using interpreter executable: /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.699 [info] Found ruff 0.1.2 at /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.699 [info] Running Ruff with: /home/userA/code/foo/.venv/bin/ruff ['format', '--force-exclude', '--quiet', '--stdin-filename', '/home/userA/code/foo/tests/utils/mongo.py']
2023-10-27 10:40:32.885 [info] Using interpreter executable: /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.885 [info] Found ruff 0.1.2 at /home/userA/code/foo/.venv/bin/ruff
2023-10-27 10:40:32.885 [info] Running Ruff with: /home/userA/code/foo/.venv/bin/ruff ['--force-exclude', '--no-cache', '--no-fix', '--quiet', '--output-format', 'json', '-', '--stdin-filename', '/home/userA/code/foo/tests/utils/mongo.py']
```

**Ruff settings:**

```toml
[tool.ruff]
cache-dir = "/tmp/.cache/ruff"
line-length = 120

# All uncommented lines should be fixed and enabled
select = [
  # These are a copy of the Ruff defaults
  # "F" is Pyflakes, "E" is pycodestyle
  "E4", "E7", "E9", "F",
  "A", # flake8-builtins
  # "B", # flake8-bugbear
  # "C4", # flake8-comprehensions
  "C90", # mccabe
  # "COM", # flake8-commas
  "D", # pydocstyle
  # "FIX", # flake8-fixme
  # "RUF100", # Ruff rule: Enforce that noqa directives are "valid"
  # "S", # flake8-bandit
  "TID", # flake8-tidy-imports
]

ignore = [
  # All these ignores should be fixed
  "D10",  # pydocstyle "Missing docstring in ..."
  "D203", # pydocstyle "one-blank-line-before-class" conflicting with D211
  "D205", # pydocstyle "1 blank line required between summary line and description"
  "D208", # pydocstyle "Docstring is over-indented"
  "D209", # pydocstyle "Multi-line docstring closing quotes should be on a separate line"
  "D211", # pydocstyle "no-blank-line-before-class" conflicting with D203
  "D212", # pydocstyle "multi-line-summary-second-line" conflicting with D213
  "D213", # pydocstyle "no-blank-line-before-class" conflicting with D212
  "D400", # pydocstyle "First line should end with a period"
  "D401", # pydocstyle "First line of docstring should be in imperative mood"
  "D404", # pydocstyle "First word of the docstring should not be "This""
  "D403", # pydocstyle "First word of the first line should be capitalized"
  "D407", # pydocstyle "Missing dashed underline after section ("Return")"
  "D415", # pydocstyle "First line should end with a period, question mark, or exclamation point"
  "D419", # pydocstyle "Docstring is empty"
  "E713", # pycodestyle "Test for membership should be `not in`"
  # These are disabled to not conflict with the Ruff formatter
  "COM812", # flake8-commas - missing-trailing-comma
  "COM819", # flake8-commas - prohibited-trailing-comma
  "D206", # pydocstyle - indent-with-spaces
  "D300", # pydocstyle - triple-single-quotes
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
```

**VS Code settings:**

```json
{
  "editor.codeActionsOnSave": {
    "source.organizeImports": "always",
    "source.fixAll.eslint": "always",
    "source.fixAll.markdownlint": "always",
    "source.fixAll.stylelint": "always",
    "source.fixAll.ruff": "always"
  },
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.suggest.localityBonus": true,
  "[python]": {
    "editor.defaultFormatter": "charliermarsh.ruff"
  },
  "python.analysis.typeCheckingMode": "basic",
  "python.analysis.completeFunctionParens": true,
  "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python"
}
```

**Comment by MichaReiser** [comment]
What version does `ruff version` print? Any chance it is different from the version VS code uses (seems to be 0.1.2)?

**Comment by buhrmann** [comment]
I seem to have the "opposite" problem, no formatting happens when I save a file in VS Code with the following snippet: 

``` python
def set_metadata(obj: Pa | Pd, 
meta: Metadata, 
    clear: bool = False) -> Pa | Pd:
    """Store table- and column-level met ...
```

The linter complains, but it will only format if I explicitly use the `Ruff: Format document` command.

The log when saving is something like

```
2023-10-27 17:09:09.972 [info] [Trace - 17:09:09] Received notification 'window/logMessage'.
2023-10-27 17:09:09.972 [info] Running Ruff with: /Users/thomas/micromamba/envs/grp/bin/ruff ['--force-exclude', '--no-cache', '--no-fix', '--quiet', '--output-format', 'json', '-', '--stdin-filename', '/Users/thomas/code/cocktail/base_images/repos/grapy/libs/core/grapy/core/io/arrow.py']
2023-10-27 17:09:09.988 [info] [Trace - 17:09:09] Received notification 'textDocument/publishDiagnostics'.
```

While the log when explicitly formatting is

```
023-10-27 17:07:42.742 [info] [Trace - 17:07:42] Received notification 'window/logMessage'.
2023-10-27 17:07:42.742 [info] Running Ruff with: /Users/thomas/micromamba/envs/grp/bin/ruff ['format', '--force-exclude', '--quiet', '--stdin-filename', '/Users/thomas/code/cocktail/base_images/repos/grapy/libs/core/grapy/core/io/arrow.py']
2023-10-27 17:07:42.762 [info] [Trace - 17:07:42] Received request 'workspace/applyEdit - (b7f0e57a-f414-4b23-bd7d-f66e1e2f5b79)'.
2023-10-27 17:07:42.763 [info] [Trace - 17:07:42] Received response 'workspace/executeCommand - (130)' in 24ms.
2023-10-27 17:07:42.772 [info] [Trace - 17:07:42] Sending notification 'textDocument/didChange'.
```

This is with the lastest versions of Ruff and extension, and everything enables, that I can think of:

``` json
"[python]": {
        "editor.formatOnSave":true,
        "editor.formatOnPaste": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.tabSize": 4,
        "editor.insertSpaces": true,
        "editor.codeActionsOnSave": {
            "source.fixAll":"always",
            "source.organizeImports": true
        },
        "python.linting.enabled": true,
        "python.linting.lintOnSave": true,
    },
```

**Comment by charliermarsh** [comment]
Hmm, that's a tricky one. Your configuration does look right, and if something were going wrong, I'd expect to see an error in the log (thank you for including those). You don't happen to have `ruff.format.run` set to `onSave`, do you?

**Comment by buhrmann** [comment]
It's working now, after a restart. I'm pretty sure I'd already tried restarting VS Code, so not sure what changed. Maybe a subtle bug in the Python plugin (t also e.g. tries to run flake8 all the time, even though it's neither installed nor configured anywhere...)

**Comment by thernstig** [comment]
Thread hijack? 😆

**Comment by thernstig** [comment]
Here is a minimal repo with the Python package `pymongo`. I would assume VS Code wants a line break due to `logging` being a standard lib whilst `pymongo` is an installed package:

```python
import logging
import pymongo

logger = logging.getLogger(__name__)

pymongo.MongoClient([])
```

VS Code will add a line break between the two import statements whilst Ruff via CLI will not.

I disabled all extensions, and enabled them one by one. Start with the Python extension (which also installed Pylance). The formatting was not done to the above.

I then enabled the Ruff extension, and now the formatting was done to the file.

So it proves it is the Ruff extension doing this.

**Comment by charliermarsh** [comment]
Can you try running the `Organize imports` code action in VS Code with Ruff installed? Import sorting in this way is treated as a separate action from code formatting.

**Comment by thernstig** [comment]
@charliermarsh now I am a bit confused.

When I run `ruff` locally I always do this with no parameters. But it is using the `pyproject.toml` as in the initial post:
`ruff format .`

That does not format/add the line break.

But saving in VS Code (also with the settings in the original post) does.

I then proceeded to check what you mentioned and I tested in https://github.com/astral-sh/ruff-vscode/issues/318#issuecomment-1784709750.

I then also saw that the **Output channel in VS Code** was using the CLI as seen in https://github.com/astral-sh/ruff-vscode/issues/318#issuecomment-1784709750. That was not me using that, it was the VS Code output channel.

**Comment by charliermarsh** [comment]
I think the confusion is perhaps that import sorting isn't part of `ruff format` -- it's part of `ruff check` (via `ruff check --fix`). In other words, import sorting is currently part of Ruff's linter, rather than Ruff's formatter, both for historical reasons and because it modifies the actual contents of the file, unlike the rest of the formatter, which is intended to keep the AST unchanged.

So if you run `ruff format .` locally, we won't resort your imports. We'll only _reformat_ them, without moving them around, deduplicating them, merging them etc.

To run import sorting locally, you'd want to do (e.g.) `ruff check --fix --select I .`

If you're using VS Code, we're probably running `Organize Imports` on save, in addition to formatting?

**Comment by thernstig** [comment]
Sorry, we both run `ruff format .` and `ruff check .` locally and none adds the formatting.

The important part is what I see in the output channel of VS Code. And when I try those commands in the CLI, it does add the line break, so those commands being run seems "wrong"?

**Comment by charliermarsh** [comment]
@thernstig - The original configuration you pasted above doesn't include `I` in the `select`. Can you confirm that you have `I` enabled in your `pyproject.toml`?

That output all looks correct to me. Most of those arguments aren't relevant for Ruff's diagnostic behavior and are instead required for LSP interoperability (e.g., we need Ruff to output JSON).

**Comment by thernstig** [comment]
The original configuration I pasted in the first post is the config I have. Nothing else.

**Comment by charliermarsh** [comment]
That line _is_ executed. That's from VS Code's `Organize Imports` command, which is either being run explicitly, or configured to run on on-save in your configuration. If you run `Organize Imports` in VS Code, and you have Ruff set to handle that command (or it's the only-installed extension that can handle it), we run Ruff with _just_ that rule to do the import sorting.

I think you should either add `I` to your `select` in your `pyproject.toml`, or disable Ruff's import sorting in the VS Code extension. It just depends on what behavior you actually _want_. Do you want Ruff to organize your imports?

**Comment by thernstig** [comment]
@charliermarsh then I think this is sorted, thank you for the patience. I understand why this happens then.

I think maybe "something" should be done?

The confusion might be a docs issue, possibly in https://github.com/astral-sh/ruff-vscode, as that mentions `"source.organizeImports": true`? Or should `Organize Imports` respect `pyproject.toml` so if `I001` is not set there, it does nothing? That might of course generate other issues for you in the future. A possible solution would be to add a `Organize Imports (forced)` to not care about `pyproject.toml`, but maybe that is even more confusing. I am brainstorming here.

The confusion stems from that I thought that even an explicit `Organize Imports` command (or having set the config below), would still respect `pyproject.toml` and Ruff settings.

```jsonc
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
```

My solution for now is to add the `I` set of rules to my `pyproject.toml` then (or at least `I001`).

Or it might be entirely possibly you believe no change should be made at all to this, and it is my mistake on assuming that the `pyproject.toml` was always respected (even while using `Organize Imports` in VS Code).

**Comment by charliermarsh** [comment]
Thanks -- I went ahead and added a note to the docs!
