### ISSUE TITLE
Support format modificationsIfAvailable

### ISSUE THREAD

**Issue by rmallampalli** [astral-sh/ruff-vscode#319]
VS Code currently has a setting `editor.formatOnSaveMode` which allows to format only the modified lines according to source control.  Currently if it is set to modifications or modificationsIfAvailable, ruff fails silently. Only setting it to file works: please consider throwing an error if the setting is changed. I would also like the modificationsIfAvailable option to be supported.

My use case is as follows: in certain codebases full files cannot be formatted as that would make reading the diffs between working state and old commits quite difficult. 

This may be related to [this open issue in the ruff repo](https://github.com/astral-sh/ruff/issues/7233).

I use the binary shipped with v2023.44.0 of the extension.
My settings file:
```JSON
    "[python]": {
        "editor.defaultFormatter": "charliermarsh.ruff",
    },
    "notebook.formatOnSave.enabled": true,
    "editor.formatOnSaveMode": "modifications",
    "inlineChat.showDiff": false,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "editor.formatOnSave": true
```

**Comment by MichaReiser** [comment]
Here a [link to the announcement of the new setting](https://code.visualstudio.com/updates/v1_49#_only-format-modified-text)
