### ISSUE TITLE
Ruff argument to skip magic trailing comma not working

### ISSUE THREAD

**Issue by jrodriigues** [astral-sh/ruff-vscode#320]
I am trying to make the ruff VS Code extension to use the arg --skip-magic-trailing-comma=true but it doesn't seem to work.

I have set it up in my pyproject.toml on the [tool.ruff.format] and it works when I run the ruff formatter from the CLI,
however, it doesn't seem to have any effect when formatting using the VS Code extension.

My VS Code settings are as follows:
```json
  "[python]": {
    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.rulers": [120],
    "editor.codeActionsOnSave": {
      "source.fixAll": true,
      "source.organizeImports": true
    }
  },
  "editor.formatOnSave": true,
  "files.autoSave": "onFocusChange",
  "ruff.format.args": ["--skip-magic-trailing-comma=true"]
```

and my pyproject.toml:
```toml
[tool.ruff]
line-length = 120
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "I",
  "ICN",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
ignore = [
  "S608",
  "FBT001",
  "FBT002",
  "C901",
  "S314",
  "PLR0912",
  "PLR0915",
]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "native"
skip-magic-trailing-comma = true
```

Am I missing something?

EDIT: Forgot to mention that the expected behavior is correct when sorting/fixing the import statements only.

**Comment by charliermarsh** [comment]
We don't currently support passing `--skip-magic-trailing-comma` as a command-line argument. You should be able to remove it in lieu of your existing `pyproject.toml`. (Passing the argument to Ruff is likely causing the command to error.) Can you try removing `"ruff.format.args": ["--skip-magic-trailing-comma=true"]`?

**Comment by jrodriigues** [comment]
Yes that fixed it, the extension is picking up correctly from the pyproject.toml now.
Great stuff, many thanks!

**Comment by charliermarsh** [comment]
No worries, sorry for the confusion!

**Comment by lgonzalezsa** [comment]
Hey, is there a configuration required for pyproject.toml to ignore or skip `%%timeit` and similar IPython magic instructions?
The magic at the beginning of the cell is preventing ruff-vscode to format and linting. I think similar happens to Pylance or Python vscode extension when I try F12 to go to the definition or code declaration.
Any reference to documentation?
