### ISSUE TITLE
The formatter isn't working.

### ISSUE THREAD

**Issue by Muzych** [astral-sh/ruff-vscode#325]
![image](https://github.com/astral-sh/ruff-vscode/assets/40785143/59b9c768-0b8e-4224-98c9-bb171a22f518)
this is my settings.json in vscode.
Today I try to edit a python file and I found that the formatter isn't working.
![image](https://github.com/astral-sh/ruff-vscode/assets/40785143/5c9b6664-74cb-4852-95db-2786bc600049)

**Comment by zanieb** [comment]
Hi!

Are you using the latest version of the extension?

**Comment by Muzych** [comment]
> Hi!
> 
> Are you using the latest version of the extension?

Sorry about I forget mention my version.
Yes, I am using v2023.12.0.

**Comment by charliermarsh** [comment]
The latest version is actually `v2023.44.0`. Do you mind upgrading? The formatter isn't supported in `v2023.12.0`.

**Comment by Muzych** [comment]
> The latest version is actually `v2023.44.0`. Do you mind upgrading? The formatter isn't supported in `v2023.12.0`.

Thank you, that is indeed the reason. I found that the version number displayed after downloading my plug-in is inconsistent with the version number in the store. It's so strange, I have no idea. Is this about proxy by any chance?

**Comment by charliermarsh** [comment]
That's very strange, though I suspect it's a VS Code error in some way and not specific to Ruff... Could you try uninstalling the extension completely, then installing it?

**Comment by Muzych** [comment]
> That's very strange, though I suspect it's a VS Code error in some way and not specific to Ruff... Could you try uninstalling the extension completely, then installing it?

I installed the latest vscode version and problem solved. It seems like the vscode auto detect the environment and choose the most compatible version for users. Thanks for your replying!
