### ISSUE TITLE
`Organize imports` and `Ruff: Format imports` apply other autofixes

### ISSUE THREAD

**Issue by trag1c** [astral-sh/ruff-vscode#328]
https://github.com/astral-sh/ruff-vscode/assets/77130613/e1ae081b-2a4b-43e9-9d3e-2046cc2a1f3a

**Comment by charliermarsh** [comment]
Can you share the relevant portion of your `settings.json`? Wasn't able to reproduce with my first attempt locally, but there could certainly be a bug here.

**Comment by trag1c** [comment]
```json
    "ruff.lint.args": [
      "--select=F,E,W,I,UP,N,S,C,B,A,T,Q,RUF,YTT,BLE,ANN,FBT,PL,TRY,RSE,SLF,DTZ,EXE,ISC,ICN,G,INP,PIE,RET,SIM,TID,TCH,ARG,PTH,PERF,SLOT",
      "--ignore=DTZ005,INP001,TCH003,ANN101,ANN102,ANN401,TID252,T201,B905,S101,TRY003,PLR2004"
    ],
```

**Comment by dhruvmanila** [comment]
I see the problem here. We should be using `--select` instead for the `only` keyword argument.

https://github.com/astral-sh/ruff-lsp/blob/a2661eff739c4b1dca4f18c73ef69bc90706dfaa/ruff_lsp/server.py#L1175-L1182

**Comment by dhruvmanila** [comment]
Hmm. Actually we would also need to check if there's `--extend-select` argument in the user config and remove that before passing it to the Ruff CLI.

**Comment by dhruvmanila** [comment]
Or, we could filter out the diagnostics to only keep the ones matching in the `only` list.

**Comment by charliermarsh** [comment]
I thought we used `argv += ["--extend-ignore", "ALL"]` to solve this problem?

**Comment by dhruvmanila** [comment]
It seems like `--ignore=ALL` isn't working:

```console
$ ruff check --no-cache --isolated src/play.py --select=I,ANN,PT --ignore=ALL
src/play.py:1:1: I001 [*] Import block is un-sorted or un-formatted
src/play.py:5:9: ANN201 Missing return type annotation for public function `test_foo`
src/play.py:5:18: ANN101 Missing type annotation for `self` in method
src/play.py:6:9: PT009 Use a regular `assert` instead of unittest-style `assertTrue`
Found 4 errors.
[*] 1 fixable with the `--fix` option (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

But,

```console
$ ruff check --no-cache --isolated src/play.py --select=I,ANN,PT --ignore=I,ANN   
src/play.py:6:9: PT009 Use a regular `assert` instead of unittest-style `assertTrue`
Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

Version:
```console
$ ruff version                                                    
ruff 0.1.4 (c4889196e 2023-11-03)
```

From the [documentation](https://docs.astral.sh/ruff/settings/#ignore), it seems like the correct behavior?
> When breaking ties between enabled and disabled rules (via select and ignore, respectively), more specific prefixes override less specific prefixes.

**Comment by charliermarsh** [comment]
@dhruvmanila - Yeah I think the use of `--ignore=ALL` won't work when users are specifying selects and ignores in their `ruff.lint.args`... Another option is we could attempt to filter out any custom `--select` or `--ignore` when running with `only`? Like literally filter out the array of arguments?

**Comment by dhruvmanila** [comment]
> Another option is we could attempt to filter out any custom `--select` or `--ignore` when running with `only`? Like literally filter out the array of arguments?

Yeah, that's likely the best option for now.

**Comment by dhruvmanila** [comment]
Thanks for the issue! This is fixed and will be available in the next release.
