### ISSUE TITLE
Allow using the formatter but not the linter

### ISSUE THREAD

**Issue by Apakottur** [astral-sh/ruff-vscode#329]
I'm using the Ruff formatter in VSCode, but would prefer to run the linter manually outside of it.
The current configuration options do not provide a way to enable the formatter but disable the linter, so I use the following hack to make it happen:

```json
...
"ruff.lint.args": [
        "--crash"
    ],
...
```

Am I missing something, and it's possible to disable the linter but not the formatter?

**Comment by dhruvmanila** [comment]
Thanks for the clear issue!

I don't think it's currently possible to disable just the linter as it's provided through the LSP interface where the diagnostics are always provided. Maybe we could provide a configuration option in `ruff-lsp` to disable diagnostics.

If possible, can you provide some details as to why you would want to run the linter outside the editor? Your use-case might help us understand this issue more clearly.

**Comment by charliermarsh** [comment]
I don't think this is supported but I did consider adding it in the past. (You could probably change `--crash` to `--ignore=ALL`.)

**Comment by Apakottur** [comment]
Thanks for the replies.

We use a very strict Ruff configuration in the project I'm working on (almost all rules enabled), so Ruff can be very noisy when writing code. For example when adding an import (which is immediately unsorted) or introducting a new variable (which is immediately unused).

Until recently we've been using the Ruff linter and the Black formatter, and I used Black in VSCode. Recently we switched to the Ruff formatter so I wanted to use the Ruff formatter in VSCode.

I realize that I might create a proprietary configuration file for the VSCode Ruff linter (in contrast to the strict one we use in pre-commit and CI), but right now I don't feel like running the Ruff linter more often than I do will increase productivity.

**Comment by T-256** [comment]
I like it. Extra `Ruff: Toggle linting` command or something like [Formatting Toggle](https://marketplace.visualstudio.com/items?itemName=tombonnike.vscode-status-bar-format-toggle) could help to get rid from external terminal ruff execution.

`Ruff: Toggle linting`: focus on writing codes without linter warnings for unfinished lines
few hours coding...
`Ruff: Toggle linting` again: now fix linter violations (if any) on finished codes.

**Comment by zpincus** [comment]
Not unrelated, it would be nice to be able to toggle linting for notebooks separately from python source...
