### ISSUE TITLE
Recover isort ordering of imports

### ISSUE THREAD

**Issue by CHDev93** [astral-sh/ruff-vscode#330]
How can I recover the `isort` import order for first party packages? I found a mention in the FAQ about setting `src = ["src"]` (which is my project structure) but I haven't managed to find out what the corresponding thing I need in my `settings.json` file.

Versions of various things are below

VSCode: 1.82.2
ruff: 0.1.4
Python: 3.10.12

settings.json
```
    "editor.formatOnSave": true,
    "[python]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.organizeImports": true
        },
        "editor.defaultFormatter": "charliermarsh.ruff"
    },
```

**Comment by charliermarsh** [comment]
Unfortunately we don't support configuring arbitrary settings from the `settings.json` file -- `src` needs to be in a `pyproject.toml` or `ruff.toml` file, but you have a few different options:

1. Add a `pyproject.toml` or `ruff.toml` file to the root of your project.
2. Add a system-wide configuration file (see the [FAQ](https://docs.astral.sh/ruff/faq/#how-can-i-change-ruffs-default-configuration)), the location will vary by OS, but for example, if you're on macOS, you'd create `/Users/Alice/Library/Application Support/ruff/ruff.toml` with:

```toml
[isort]
src = ["src"]
```

**Comment by CHDev93** [comment]
Okay, that explains why I wasn't able to find the argument! Will go ahead and configure the toml file.
