### ISSUE TITLE
Pop-up warning that standard library files are being skipped

### ISSUE THREAD

**Issue by Nicholas-Autio-Mitchell** [astral-sh/ruff-vscode#331]
If I `control`/`command`-hover over import statements, more specifically over import symbols coming from outside my own project, I see the following warning pop-ups appear, coming from this extension:

![image](https://github.com/astral-sh/ruff-vscode/assets/12820901/22703265-ee95-4fe3-af71-beeeb31aa415)

**TLDR: how do I prevent these pop-ups from appearing? I am actually fine with ruff not analysing those files.**

I looked into blocking them from the vscode side, but [based on this SO post](https://stackoverflow.com/questions/44863450/how-do-you-disable-warning-and-error-popups-in-vscode), it isn't something vscode supports, and will not in the future.

[There is this issue](https://github.com/astral-sh/ruff-vscode/issues/232), talking about how `ruff` can sometimes run on standard library files when it is not desired - so a bit of a different issue to this one. 

It feels like changing the filters (as suggested in the above linked issue) is not really going to change anything here, apart from maybe allowing ruff to simply analyse everything... which I don't want.

Any other ideas? 

### versions & settings

<details>

<summary>Click to reveal</summary>

### vscode
Version: 1.85.0-insider
Commit: e55009850900a64eeb37b2228c79855ceff63914
Date: 2023-11-03T15:12:22.246Z

### Ruff extension

v2023.44.0

### Ruff settings

![image](https://github.com/astral-sh/ruff-vscode/assets/12820901/c9da2c2a-9c3c-49e3-a922-722cac3548fd)

</details>

**Comment by charliermarsh** [comment]
I think there's supported to be a "Show Notifications" setting, I see it in my own VS Code pane, but for some reason it's not visible in your screenshot?

<img width="443" alt="Screen Shot 2023-11-07 at 11 43 19 AM" src="https://github.com/astral-sh/ruff-vscode/assets/1309177/7b508266-d4ff-4854-b70e-9516e3adcd57">

**Comment by Nicholas-Autio-Mitchell** [comment]
I also expected to see that, but it is not visible. If I expand the popups, it just shows the warning message text, but no other options.

![image](https://github.com/astral-sh/ruff-vscode/assets/12820901/722d54c3-43d5-437b-a607-344570a6c7aa)

I do not have the trace server trace enabled (just saw the bottom of your screenshot), but I played with all options of that setting and it didn't change anything.

The little cog-wheel only gives the option to "Manage this extension".

**Comment by Nicholas-Autio-Mitchell** [comment]
Using the extension's bundled version of ruff verses from my env also doesn't make a difference.

**Comment by charliermarsh** [comment]
And -- just to confirm -- you're on the latest version of the extension?

**Comment by Nicholas-Autio-Mitchell** [comment]
Extension version: `v2023.44.0`

All version info is in my original post above (must be expanded).

**Comment by Nicholas-Autio-Mitchell** [comment]
More info: this is over a remote session.

From the extension's page, In case it helps you:

![image](https://github.com/astral-sh/ruff-vscode/assets/12820901/4d846ac4-b9e0-4bb5-965d-f09c7d445a68)

**Comment by charliermarsh** [comment]
Thanks. I'm just trying to figure out why the setting isn't appearing for you. It's the only setting that uses `"scope": "machine"`, could that somehow be related...?

```json
"ruff.showNotifications": {
  "default": "off",
  "markdownDescription": "Controls when notifications are shown by this extension.",
  "enum": [
    "off",
    "onError",
    "onWarning",
    "always"
  ],
  "enumDescriptions": [
    "All notifications are turned off, any errors or warning are still available in the logs.",
    "Notifications are shown only in the case of an error.",
    "Notifications are shown for errors and warnings.",
    "Notifications are show for anything that the server chooses to show."
  ],
  "scope": "machine",
  "type": "string"
}
```

**Comment by charliermarsh** [comment]
I'm playing around to confirm that the setting works as intended, since you can maybe just set it in your `settings.json`.

**Comment by charliermarsh** [comment]
Can you try adding this to your `settings.json`?

```json
{
    "ruff.showNotifications": "off"
}
```

**Comment by Nicholas-Autio-Mitchell** [comment]
Ok, I found the problem. I was looking at my User settings and the Workspace settings - didn't realise the the `scope: "machine"` means that the setting itself only appears in the (in my case) remote workstation's settings.

Setting that does work as expected :)

![image](https://github.com/astral-sh/ruff-vscode/assets/12820901/ad10c668-4db2-4eee-8053-63e9b6864f32)

Adding those configs to User/Workspace `settings.json` has no effect - must be in `/home/username/.vscode-server-insiders/data/Machine/settings.json`.  Makes sense in retrospect, although would be nice to also be exposed in User settings IMO.

**Comment by charliermarsh** [comment]
Oh interesting! Using `"machine"` for this setting follows the official VS Code extension template (https://github.com/microsoft/vscode-python-tools-extension-template/blob/main/package.json), but I agree that's a little confusing. \cc @karthiknadig in case you have thoughts on it.

**Comment by karthiknadig** [comment]
@charliermarsh We can relax the scope on this. I would avoid `resource` scope.

There is only one server process that acts as a coordinator for all the roots (in multi-root case). This setting applies to that server, and not the runners which are scoped per root. `resource` scope setting applies to each of the runners. And setting this at resource level can become an issue if there are problems at the coordinator level.

**Comment by TheRealBecks** [comment]
@karthiknadig @charliermarsh This seems to be exactly the problem described in #232 - when I get that popup message I also see the ruff messages in the console.
