### ISSUE TITLE
[Request] Quick Fix menu: add file-level `# ruff: noqa: ...` comment to suppress warning

### ISSUE THREAD

**Issue by pep-sanwer** [astral-sh/ruff-vscode#332]
Similar to https://github.com/astral-sh/ruff-vscode/issues/148, but at the file level ala https://github.com/astral-sh/ruff/issues/2446

Thank you for your incredible, game-changing toolset!

**Comment by zanieb** [comment]
I requested this at https://github.com/astral-sh/ruff-lsp/issues/253 — let's converse there.

Glad you like it!
