### ISSUE TITLE
Format Document command delete entire code including invalid code

### ISSUE THREAD

**Issue by beskep** [astral-sh/ruff-vscode#338]
When executing "Format Document" command on code containing the following line, the entire code is deleted.
`d={'a': 'b', ''}`

Whereas ParseError occurs when formatting by terminal.

**Comment by charliermarsh** [comment]
Do you mind checking if you're on the latest version of the extension (2023.48.0)? We published a fix for this earlier tonight.

**Comment by beskep** [comment]
> Do you mind checking if you're on the latest version of the extension (2023.48.0)? We published a fix for this earlier tonight.

**Comment by beskep** [comment]
> Do you mind checking if you're on the latest version of the extension (2023.48.0)? We published a fix for this earlier tonight.

It was v2023.46.0.

**Comment by charliermarsh** [comment]
Okay, thanks. Did upgrading resolve the issue for you?

**Comment by beskep** [comment]
It is resolved.
Thank you for the answer. :)

**Comment by charliermarsh** [comment]
Awesome, so glad to hear it!
