### ISSUE TITLE
module level E402 inside notebook cells

### ISSUE THREAD

**Issue by alexdauenhauer** [astral-sh/ruff-vscode#340]
This seems to have just recently started, but I am getting an error for E402 when the import is in the next cell down. I think this rule should operate on a per cell basis, rather than throwing an error if all my imports are not at the top of the notebook.

![image](https://github.com/astral-sh/ruff-vscode/assets/11903445/0a8a2b19-87a3-4dfb-8bc7-33f0826301ca)

**Comment by yuuuxt** [comment]
Having the same issue. As a workaround, I created a `ruff.toml` (in home folder or specific project folder):
```toml
[lint.per-file-ignores]
"*.ipynb" = ["E402"]
```

**Comment by dhruvmanila** [comment]
Hey, thanks for opening this issue. Currently, we recommend to ignore that rule as suggested by @yuuuxt but I think we can do something here for notebooks. I've opened a general tracking issue around this as there are other rules which needs special handling in notebooks. I'll merge this with https://github.com/astral-sh/ruff/issues/8669
