### ISSUE TITLE
Every time I save a certain python file in my directory, a different one is automatically executed

### ISSUE THREAD

**Issue by pitosalas** [astral-sh/ruff-vscode#344]
Why am I posting here? Because when I uninstall the Ruff extension that stops happening. I tried to look at the Ruff settings but I can't locate what is causing this. 

Weird. Can anyone shed some light?

**Comment by dhruvmanila** [comment]
Can you provide additional context on this issue? When you say "a different one is automatically executed", do you mean that Ruff is linting that file or do you actually mean that the code is being executed? What is your VS Code configuration related to Python and Ruff?

**Comment by pitosalas** [comment]
Thanks for the response. I am sorry but I now don’t think it’s Ruff. The
mystery continues. But fyi, basically here’s what happens.

I have been working on several python programs all in one directory. I’ve
had Ruff and some other extensions enabled.

These are standalone .py files that is they will run and produce output.

Right now, say I am editing file one.py. It seems that each time save (with
command-s) my edit of one.py it also automatically runs two.py.

Again, it’s a mystery. But I am pretty sure Ruff is innocent. Sorry for the
false alarm. However if you have an idea that will help me troubleshoot
this annoying behavior I would be appreciative.

Best,

Pito Salas
Computer Science Faculty
Brandeis University

**Comment by dhruvmanila** [comment]
Thanks!

I think what you could do is disable all relevant extensions and enable one at a time. Also, it could be that an extension is actually running the _current_ file and it might be importing the other file which then seems like the other file is running.
