### ISSUE TITLE
[Question] Can this extension lint all Python files in the project (instead of just opened files)?

### ISSUE THREAD

**Issue by abceleung** [astral-sh/ruff-vscode#346]
I think it is possible (by changing _ruff.lint.args_ maybe?), but not sure how.
I tried setting "ruff.lint.args": ["."]" but it didn't work.

VSCode Mypy can do this via `"mypy-type-checker.reportingScope": "workspace"`. 
There is also `"typescript.tsserver.experimental.enableProjectDiagnostics": true` for Typescript.

Edit: Bonus mark if I can exclude specific folders (like `.venv`) while linting all other files

**Comment by charliermarsh** [comment]
@abceleung -- We don't support that yet, but it has been requested in #145 and a few other folks have asked about it too, so we will likely add it in the future.

**Comment by charliermarsh** [comment]
(Just closing to merge into #145.)
