### ISSUE TITLE
Should Ruff Autoformat respect # noqa / # fmt

### ISSUE THREAD

**Issue by bmaingret** [astral-sh/ruff-vscode#347]
Hi,

Thanks for this very useful extension.
I have an issue with the formatting behavior (that I use with `onSave`).

Shouldn't the formatting applied by Ruff respect the `# noqa` and similar ?

For instance: 

Before formatting :

![image](https://github.com/astral-sh/ruff-vscode/assets/1751970/9a4d6992-d60a-4640-a4e6-63138959e844)

After : 

![image](https://github.com/astral-sh/ruff-vscode/assets/1751970/8a6d1a61-1fd4-4885-a1e1-93276cbd4fe5)

 I would expect : 

![image](https://github.com/astral-sh/ruff-vscode/assets/1751970/e476808a-8a75-4e0d-9e96-400c19fe6697)

Thanks a lot

**Comment by charliermarsh** [comment]
For the formatter, the suppression comments are a little different. You can add `# fmt: skip` to the end of a statement to skip formatting, like:

```python
my_line_too_long = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" # fmt: skip
```

You can also add `# fmt: off` anywhere, and we'll disable formatting until we see a `# fmt: on`.

**Comment by bmaingret** [comment]
I think I tried this one, but in a multiline. 
Has to be at the very of end of the multiline ! 

Thanks a lot
