### ISSUE TITLE
Trigger re-run of ruff on the whole code base

### ISSUE THREAD

**Issue by rngadam** [astral-sh/ruff-vscode#349]
We use ruff as part of our continuous build:

![image](https://github.com/astral-sh/ruff-vscode/assets/538542/21eaaf49-c46a-4360-b225-a989bf307544)

Because we have ruff warnings, I checked out the source in Codespace.

I have the ruff-vscode extension installed.

I'd expect to have the same list of linting issues in my Problems views.

There are only options to run on save and run on type in the configuration.

The commands palette doesn't seem to have a way to trigger for all the source:

![image](https://github.com/astral-sh/ruff-vscode/assets/538542/ae0acccc-440c-4e58-b2c2-6ee73e8ea1d7)

## WORKAROUND

```bash
pip install ruff
ruff check .
```

and then open each file that has warnings at the command-line.

**Comment by charliermarsh** [comment]
I think this might be the same #145 -- does that seem right?

**Comment by charliermarsh** [comment]
(Merging into #145.)
