### ISSUE TITLE
Ruff doesn't work with virtual environment

### ISSUE THREAD

**Issue by Vinci08** [astral-sh/ruff-vscode#351]
Hello, I am having trouble get ruff to lint files inside a python virtual environment. The issue here is I kept getting warnings like this
 `Skipping standard library file: c:\Users\Leo\Desktop\someproject\api\_views\reports.py`

here is my settings.json for ruff
```
	"ruff.interpreter": [
		"${workspaceFolder}\\scripts\\python.exe"
	],
	"python.defaultInterpreterPath": "${workspaceFolder}\\scripts\\python.exe",
	"[python]": {
		"editor.formatOnSave": true,
		"editor.codeActionsOnSave": {
			"source.fixAll": true,
			"source.organizeImports": true
		},
		"editor.defaultFormatter": "ms-python.black-formatter"
	},
```

Please give me some guidance on how to fix this issue. Thank you

**Comment by Vinci08** [comment]
@charliermarsh hi Charlie,

This is the input from `print(site.getsitepackages())`

`['C:\\Users\\Leo\\Desktop\\someproject', 'C:\\Users\\Leo\\Desktop\\someproject\\lib\\site-packages']`

This is the input from `print(site.getusersitepackages())`

`C:\Users\Leo\AppData\Roaming\Python\Python38\site-packages`

Thank you

**Comment by Vinci08** [comment]
@CrystalWindSnake hi Crystal, I used virtualenv, so the virtual environment directory is inside the project code, not the the other way around. At least that's how I interpret venv should be - different environments for different projects. Thank you.

**Comment by hansalemaos** [comment]
@CrystalWindSnake Sometimes it is unavoidable. I have just installed this extension, and have had the same problem (with Anaconda). This hack resolves the problem, but please add it as a check-box in the configuration. 

```
# file on my hdd: C:\Users\xxx\.vscode\extensions\charliermarsh.ruff-2024.2.0-win32-x64\bundled\libs\ruff_lsp\server.py
# Hack 1:
# Comment out:

if document.is_stdlib_file():
   log_warning(f"Skipping standard library file: {document.path}")
   return None

# updated code should look like:

async def _run_format_on_document(document: Document) -> ExecutableResult | None:
    """Runs the Ruff `format` subcommand on the given document source."""
    # if document.is_stdlib_file():
    #    log_warning(f"Skipping standard library file: {document.path}")
    #    return None
	
async def _run_check_on_document(
    document: Document,
    *,
    extra_args: Sequence[str] = [],
    only: Sequence[str] | None = None,
) -> ExecutableResult | None:
    """Runs the Ruff `check` subcommand  on the given document source."""
    # if document.is_stdlib_file():
    #    log_warning(f"Skipping standard library file: {document.path}")
    #    return None

# Hack 2 (not tested):

def is_stdlib_file(self) -> bool:
	"""Return True if the document belongs to standard library."""
	return False # add this line
	return utils.is_stdlib_file(self.path) # ignored now
```

**Comment by charliermarsh** [comment]
@karthiknadig -- Have you seen this with any of the other extensions?

**Comment by Vinci08** [comment]
> @karthiknadig -- Have you seen this with any of the other extensions?

I can confirm that ms-pylint has the same issue with virtual environment. This was the reason I looked into ruff.

**Comment by hansalemaos** [comment]
I'm moving from PyCharm to VsCode, and this was the first linter that worked in my Anaconda envs (with the hack though). By the way: It seems like doing a great job. Thank you for the great work!

**Comment by karthiknadig** [comment]
How is the project structured. This is what we expect:
```
project_dir
|- virtualEnv
|    |- lib
|        |- site-packages
|    |- bin
|        |- python
|- your_script.py
|- your_module
|    |- module_files.py
```

can you share your project structure?

**Comment by charliermarsh** [comment]
> By the way: It seems like doing a great job. Thank you for the great work!

Thank you so much :)

Right now I'm leaning towards adding a setting to allow folks to opt-out of this behavior.

**Comment by jdegenstein** [comment]
@hansalemaos I tried your workaround (hack 1), and I am getting some crashes.
```
ERROR Future exception was never retrieved
future: <Future finished exception=BrokenPipeError(32, 'The pipe has been ended', None, 109, None)>
Traceback (most recent call last):
  File "C:\Users\xxx\.conda\envs\ocp_vscode\Lib\asyncio\subprocess.py", line 152, in _feed_stdin
    await self.stdin.drain()
...
```
Not sure what I did wrong. Tried restarting VSCode/ruff a few times and the same result.

**Comment by hansalemaos** [comment]
@karthiknadig I guess that you are asking @Vinci08, right? I am using anaconda. 
@charliermarsh You are welcome! :) 
An opt-out would be great, because I frequently change things in lib/site-packages (modules that I wrote or sometimes monkey patches for other modules). And a linter would help there too! 
Besides that, I often put py files directly in the env folder when I compile code with Nuitka or PyInstaller. That makes things much easier.

**Comment by hansalemaos** [comment]
> @hansalemaos I tried your workaround (hack 1), and I am getting some crashes.
> 
> ```
> ERROR Future exception was never retrieved
> future: <Future finished exception=BrokenPipeError(32, 'The pipe has been ended', None, 109, None)>
> Traceback (most recent call last):
>   File "C:\Users\xxx\.conda\envs\ocp_vscode\Lib\asyncio\subprocess.py", line 152, in _feed_stdin
>     await self.stdin.drain()
> ...
> ```
> 
> Not sure what I did wrong. Tried restarting VSCode/ruff a few times and the same result.

I am using 1+2 combined now, and it is working. But it seems like, there will be a patch soon according to: @charliermarsh 

This is the first and only code so far that I have used to test it 
```python
import pandas as pd
import numpy as np  # working here
from PrettyColorPrinter import add_printer
def bsbsbs(x=4, y=22):
    return x**x**y **zz # working here
kj;j # working here
add_printer(1)
df = pd.read_csv("C:\Users\xxx\Downloads\titanic.txt")  # working here
```

**Comment by Vinci08** [comment]
@karthiknadig I usually create new project folder (let's call it project_dir), then run `virtualenv .` at project folder level to create the virtual environment. This is my usual structure:

> project_dir
> |- my_module
> |          |- module_files.py
> |- Scripts
> |- Lib
> |- my_script.py
> |- requirements.txt
> |- .gitignore

I put Lib and Script folder .gitignore, so the only thing makes it to source control is requirements.txt.

**Comment by karthiknadig** [comment]
That structure is not recommended. Please follow the one I posted. Soon `venv` (the python package) on creation will add a `.gitignore` (`*`) that will ignore the entire directory for source control. This is intentional as the directory is supposed to be destructible.

You can also use `Python: Create Environment` to create `venv` or `conda` envs. It will create them with the structure that we recommend.

**Comment by hansalemaos** [comment]
> That structure is not recommended. Please follow the one I posted. Soon `venv` (the python package) on creation will add a `.gitignore` (`*`) that will ignore the entire directory for source control. This is intentional as the directory is supposed to be destructible.
> 
> You can also use `Python: Create Environment` to create `venv` or `conda` envs. It will create them with the structure that we recommend.

Drinking beer is also not recommended, but a lot of people drink. :) Don't you think there is a way to add a little checkbox in the settings to disable this behaviour. I would help those outlaws out there :)

**Comment by charliermarsh** [comment]
I am somewhat tempted to remove this check altogether and put the onus on Ruff and the user's Ruff configuration to filter out these kinds of things.

**Comment by hansalemaos** [comment]
Awesome!!!

**Comment by charliermarsh** [comment]
Setting (to opt-out) will go out in the next release (tomorrow, I gotta sleep and would prefer not to release and leave in case there are issues).
