### ISSUE TITLE
Unknown fields for [tool.ruff.lint.isort]

### ISSUE THREAD

**Issue by einarwar** [astral-sh/ruff-vscode#354]
I was very pleased when https://github.com/astral-sh/ruff/pull/8841 was released. However, when i tried to modify my setup and replace isort with ruff-isort, i was not able to get auto-formatting using the VSCode extension.

Running Ruff VSCode extension v2023.50.0 with import strategy set to `fromEnvironment`.
Running Ruff 0.1.7

Minimal `pyproject.toml`
```toml
[tool.ruff]
select = ["I"]
[tool.ruff.lint.isort]
length-sort = true
```

When checking ruff output in vscode, i get the following

```text
2023-12-11 15:19:52.124 [info] ruff failed
  Cause: TOML parse error at line 15, column 1
   |
1  | [tool.ruff]
   | ^^^^^^^^^^^
unknown field `length-sort`, expected one of `force-wrap-aliases`, `force-single-line`, `single-line-exclusions`, `combine-as-imports`, `split-on-trailing-comma`, `order-by-type`, `force-sort-within-sections`, `case-sensitive`, `force-to-top`, `known-first-party`, `known-third-party`, `known-local-folder`, `extra-standard-library`, `relative-imports-order`, `required-imports`, `classes`, `constants`, `variables`, `no-lines-before`, `lines-after-imports`, `lines-between-types`, `forced-separate`, `section-order`, `no-sections`, `detect-same-package`, `sections`
```
I might be totally wrong here, but it seems like the extension is using an old json-schema at https://json.schemastore.org/ruff.json this might be the issue, and an update to the schema is the only thing needed.

If this is the case, would it be an idea if `fromEnvironment` is set to True, that the json-schema from the ruff package is used instead of the one from the json schemastore? I might be oversimplifying this, and i also understand that the extension must be available to use without the package.

**Comment by charliermarsh** [comment]
Ah yeah, we need to update the JSON Schema in schemastore. Unfortunately, that's just a process that's entirely separate from the release, and so the version in schemastore is occasionally out-of-sync with `main`.

**Comment by charliermarsh** [comment]
I've updated the schema in https://github.com/SchemaStore/schemastore/pull/3436. This should be resolved once that's merged.

**Comment by einarwar** [comment]
Wow, that was fast. Thanks!
