### ISSUE TITLE
is --line-length argument working?

### ISSUE THREAD

**Issue by BartolomeSintes** [astral-sh/ruff-vscode#357]
I am using VSCode 1.85 with Ruff extension updated (0.1.5).
I am trying to set the limit-length argument, but the E501 is not showing.
I think some screenshots will be useful in order to explain the issue:
My program is just two lines: one with an f-string without placeholders (line 2) and another one with a long line (line 3, 135 characters long). The F541 warning is shown as expected:
![2023-12-12-1](https://github.com/astral-sh/ruff-vscode/assets/1515413/0430f17b-9c49-4aed-9844-9436f4d89f5f)
If I ignore the F541 warning in settings.json, the warning is not shown anymore:
![2023-12-12-2](https://github.com/astral-sh/ruff-vscode/assets/1515413/112527f5-f8b7-4b73-b6ea-c87450f31340)
So ruff seems to be working as expected, but the E501 is not shown.
I understand that line length must be set in ruff.lint.args, as explained in https://github.com/astral-sh/ruff/pull/8363
Am I doing something wrong or is it a ruff extension bug?
Thanking you in advance,
Bartolomé Sintes

**Comment by charliermarsh** [comment]
Sorry for the confusion -- we no longer include `E501` in the default rule set, so you need to add `--select=E501` or `--select=E` to your `ruff.lint.args`.

**Comment by charliermarsh** [comment]
You can see the default configuration at the top here: https://docs.astral.sh/ruff/configuration/

**Comment by BartolomeSintes** [comment]
Thank you for your fast answer. You are completely right. 
When I read the [pull 8363](https://github.com/astral-sh/ruff/pull/8363), "Add --line-length option to format command" I did not realize it was a pull in the ruff repository, not in the ruff-vscode one. I supposed that line-length should be added to the ruff.format.args section, not to the ruff.lint.args as it should. My mistake, sorry.
Keep your very good work!

**Comment by jmakov** [comment]
What's even more confusing to me is running `ruff check --line-length 10 my.py` doesn't return any errors.

**Comment by charliermarsh** [comment]
@jmakov -- Per the above, you need to enable the line-length rule -- it's not included by default, since it often conflicts with using a formatter. Can you try adding `--extend-select=E` to your command and configuration?

**Comment by jmakov** [comment]
> @jmakov -- Per the above, you need to enable the line-length rule -- it's not included by default, since it often conflicts with using a formatter. Can you try adding `--extend-select=E` to your command and configuration?

Thank you for the quick response. Yes, that works. Would expect a flag to overwrite everything when the user uses it. Anyhow, my probl is solved, thanks.

**Comment by dhruvmanila** [comment]
@romanholidaypancakes I'm assuming that you're using [`ruff-lsp`](https://github.com/astral-sh/ruff-lsp) as you're using `ruff.format.args` setting. I'd suggest to [migrate to using the native server](https://docs.astral.sh/ruff/editors/migration/).

Regardless, the `--extend-select` flag is part of the linter but you're providing it for the formatter which is why it must be causing an error.

**Comment by dhruvmanila** [comment]
> No error is reported, but the string is not formatted when the length is exceeded

Can you share a minimal source code on which you're running Ruff? I'm guessing that it's a long string and your expectation is that the string should break once it goes beyond the line length. Is that correct? If so, then that's not currently supported, it can be tracked here: https://github.com/astral-sh/ruff/issues/6936.

**Comment by dhruvmanila** [comment]
> Yes, for example, if I set the maximum length to 130, then the excess will be automatically formatted. I remember using ruff before and it worked fine.

Yeah, that is not yet supported, refer to the linked issue.
