### ISSUE TITLE
Rust version mismatch error when saving a python file

### ISSUE THREAD

**Issue by siraj-samsudeen** [astral-sh/ruff-vscode#370]
I installed Ruff on my MacbookPro M2 and updated settings.json as per instructions to formatonSave and when I save, I get this error:
Ruff <0.2.0,>=0.0.291 required, but found 0.0.287 at /opt/homebrew/bin/ruff

**Comment by charliermarsh** [comment]
It looks like you have an older version of Ruff installed. The formatter was added in Ruff 0.0.291, so you'll need to upgrade. How did you install Ruff this time? Can you try removing it from Homebrew?

**Comment by siraj-samsudeen** [comment]
I just installed the VSCode extension assuming ruff is just already packaged there. I did not even know ruff was already available through Jupyterlab. I did brew upgrade ruff and it resolved the problem. Thank you so much for the quick response.

From: Charlie Marsh ***@***.***>
Date: Wednesday, 20 December 2023 at 11:01 AM
To: astral-sh/ruff-vscode ***@***.***>
Cc: Siraj Samsudeen ***@***.***>, Author ***@***.***>
Subject: Re: [astral-sh/ruff-vscode] Rust version mismatch error when saving a python file (Issue #370)

It looks like you have an older version of Ruff installed. The formatter was added in Ruff 0.0.291, so you'll need to upgrade. How did you install Ruff this time? Can you try removing it from Homebrew?

**Comment by charliermarsh** [comment]
@siraj-samsudeen -- No worries! The extension _does_ come bundled with Ruff, but if you have Ruff installed outside of the extension, then it defers to your existing installation. In other words, the bundled version of Ruff is treated as a fallback. So, another option is for you to remove your Homebrew installation altogether.
