### ISSUE TITLE
 Ruff JSON Schema in schemastore out of sync with `0.1.8` / `0.1.9`

### ISSUE THREAD

**Issue by pep-sanwer** [astral-sh/ruff-vscode#372]
on `ruff` `0.1.8` & `0.1.9`

Encountering missing schema for `tool.ruff.format`. Looks like https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/ruff.json / https://github.com/astral-sh/schemastore/blob/master/src/schemas/json/ruff.json is out of sync with https://github.com/astral-sh/ruff/blob/main/ruff.schema.json

Continuously grateful for this incredible tool!

**Comment by charliermarsh** [comment]
Thank you so much! We're working on a PR to update the SchemaStore, sorry for the delay.

**Comment by MichaReiser** [comment]
The referenced PR is now merged. @pep-sanwer could you give it another try (you may need to restart your IDE, in case it caches the schema)
