### ISSUE TITLE
Fails to Find Config

### ISSUE THREAD

**Issue by thatcort** [astral-sh/ruff-vscode#377]
I get the following error in VSCode when opening a Python file:

```Ruff: Lint failed (ruff failed Cause: Failed to parse `/development/explore/"/development/explore/.ruff.toml"`: No such file or directory (os error 2) )```

It seems to be adding the workspace location as a prefix to the full path to the config file. `/development/explore/.ruff.toml` is the correct path and the config file exists there. I'm not sure why it is doing this. Is there a setting somewhere that could be affecting this?

**Comment by charliermarsh** [comment]
That's odd, do you have anything in your `settings.json`?

**Comment by thatcort** [comment]
I found the problem. It was in one of the many settings.json files.
