### ISSUE TITLE
organizeImports buggy in vscode

### ISSUE THREAD

**Issue by HenrikZabel** [astral-sh/ruff-vscode#382]
When using `"editor.codeActionsOnSave": { "source.organizeImports": true }` my whole code jumps in vscode.

Python version: 3.11.4
Ruff version: v2024.0.0
OS: Windows 10 Home

**Comment by zanieb** [comment]
@HenrikZabel could you provide a bit more detail about the behavior you're seeing and the behavior you'd prefer?

**Comment by charliermarsh** [comment]
Closing for now, can always re-open if we receive more info.

**Comment by HenrikZabel** [comment]
I am sorry for the delay:


Basically, the whole code always "jumps" when I save my file. It seems that Ruff needs a relatively long time to sort the imports. Also, the imports are sorted when I save once and then when I save again, all the imports are totally mixed up. Especially when I have many imports from a library, I notice that Ruff takes a relatively long time. Example:

```py
from .serializers import (
    AccountSerializer,
    EmailSerializer,
    NameSerializer,
    RegistrationSerializer,
    UsernameSerializer,
)
```

If I then immediately save the file again, it looks like this:

```py
from .serializers import (AccountSerializer, EmailSerializer, NameSerializer, RegistrationSerializer, UsernameSerializer)
```

**Comment by charliermarsh** [comment]
Is it possible that you have some other extension that's interfering? Ruff wouldn't sort imports in that style, it doesn't even support it.

**Comment by HenrikZabel** [comment]
I completely reinstalled Python and now the problem is gone. So I think the problem was actually not with Ruff, but with something else. I apologize

**Comment by charliermarsh** [comment]
Oh that's great!
