### ISSUE TITLE
Verify Extension Domain Ownership

### ISSUE THREAD

**Issue by Barzi-Ahmed** [astral-sh/ruff-vscode#384]
Please verify your extension domain on VSCode marketplace to increase trust, security, seo, and get verification badge.

**Comment by charliermarsh** [comment]
Oh thanks, I'll look into this.

**Comment by charliermarsh** [comment]
I just added this to our DNS and submitted for review.

**Comment by charliermarsh** [comment]
Woohoo:

![Screenshot 2024-01-23 at 10 35 31 PM](https://github.com/astral-sh/ruff-vscode/assets/1309177/f82a486e-30eb-4807-8a33-64c103ee3730)
