### ISSUE TITLE
"Disable for this line" appears before auto-imports in Quick Fix menu

### ISSUE THREAD

**Issue by omerfarukdogan** [astral-sh/ruff-vscode#392]
I have noticed that ruff suggestions sometimes appear before the auto-import actions in the quick fix menu. It would be better if they appeared below them as disabling the rule would be the least favorable action in case of a missing import.

![thumbnail_image003](https://github.com/astral-sh/ruff-vscode/assets/8117265/8ead0e28-e36b-471d-b8e3-f2631713d4fa)

**Comment by charliermarsh** [comment]
Unfortunately I'm not sure whether we can control this, since the `Add "..."` actions come from another extension.

**Comment by dhruvmanila** [comment]
There have been some requests on the VS Code side to solve this but they're all closed:
- https://github.com/microsoft/vscode/issues/152845
- https://github.com/microsoft/vscode/issues/62267

This is how VS Code sorts them: https://github.com/microsoft/vscode/blob/a8f73340be02966c3816a2f23cb7e446a3a7cb9b/src/vs/editor/contrib/codeAction/browser/codeAction.ts#L40-L63.

If you don't find this specific type of code action useful ("Disable this rule for the line"), you can disable them with `"codeAction.disableRuleComment.enable": false`  (https://github.com/astral-sh/ruff-vscode#settings).

I'll close this issue as I don't think we can take any action from our side to resolve this.

**Comment by taylorhughes** [comment]
Had the same problem — `"codeAction.disableRuleComment.enable": false` resolved this for me

**Comment by GutiCW** [comment]
Wouldn't it make sense for Ruff to provide this "Add import" quick fix?
So one wouldn't have to rely on other extensions (e.g., PyLance).
