### ISSUE TITLE
Fail to recognize the Ruff config file path in the VSCode settings.json

### ISSUE THREAD

**Issue by ArcticOc** [astral-sh/ruff-vscode#413]
## Environment

Ruff: v2024.12.0
VSCode: 1.86.2 (Universal)
OS: Mac Os 14.3

## Description

```
"ruff.lint.args": [
      "--config=$HOME/.config/pyproject.toml"
    ],
```
Here is the error message.
```
Ruff: Lint failed (error: invalid value '$HOME/.config/pyproject.toml' for '--config <CONFIG_OPTION>' tip: A `--config` flag must either be a path to a `.toml` configuration file or a TOML `<KEY> = <VALUE>` pair overriding a specific configuration option It looks like you were trying to pass a path to a configuration file. The path `$HOME/.config/pyproject.toml` does not exist For more information, try '--help'. ) 
```
This path value used to be fine, but it seems to be invalid after the most recent update to Ruff or VSCode.

Thanks!

**Comment by MichaReiser** [comment]
Hmm. It could be because we fail to expand $HOME.

**Comment by erjac77** [comment]
We have the same problem using environment variables like `${env:PYTHON_VERSION}` in path.

```json
"ruff.path": [
  "${workspaceFolder}/dist/export/python/virtualenvs/ruff/${env:PYTHON_VERSION}/bin/ruff"
]
```

The error message:

```
Interpreter executable (/workspace/dist/export/python/virtualenvs/ruff/${env:PYTHON_VERSION}/bin/ruff) not found
```

Seems like predefined variables are expanded, but not the [environment variables](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables).

**Comment by calico-niko** [comment]
@ArcticOc Use `${userHome}` instead of `$HOME` should work.

**Comment by alkatar21** [comment]
I have a similar problem:
```jsonc
    "ruff.format.args": [
        "--config",
        "~/AppData/Roaming/Code/User/pyproject.toml",
    ],
```
This worked fine until `2024.10.0` and throws the following error since `2024.12.0`:
```log
[info] error: invalid value '~/AppData/Roaming/Code/User/pyproject.toml' for '--config <CONFIG_OPTION>'
```

**Comment by charliermarsh** [comment]
Yeah, we're failing to expand things there. I will fix now.

**Comment by charliermarsh** [comment]
Fix here: https://github.com/astral-sh/ruff/pull/10219
