### ISSUE TITLE
Ruff extension not showing up when using Vscode Remotely

### ISSUE THREAD

**Issue by pitosalas** [astral-sh/ruff-vscode#417]
I am using vscode over a network, vpn, to a cluster to a vm running ubuntu. It works perfectly. 

I am not sure if this is supported but when I look to install the ruff plug in that does formatting (this one) it does not show up on the list of available extensions.

<img width="494" alt="Screenshot 2024-02-28 at 11 00 02 AM" src="https://github.com/astral-sh/ruff-vscode/assets/44681/4da43858-d37f-4c90-bbc9-00025d5cd3ee">

Do you know if this is unsupported?

**Comment by dhruvmanila** [comment]
Hey, thanks for the issue. Can you confirm if your screenshot is correct? It seems that the extension _does_ show up. Can you give us the search query?

**Comment by pitosalas** [comment]
Thank you. What I meant is that it does show up as installed but I cannot
pick it as a formatter. Does that make sense?

**Comment by MichaReiser** [comment]
> Thank you. What I meant is that it does show up as installed but I cannot
pick it as a formatter. Does that make sense?

Do you mean that ruff doesn't show up when you do `Format Document with...` ?

**Comment by pitosalas** [comment]
Yes. Or when wanting to set it up as the default formatter.

**Comment by MichaReiser** [comment]
What version of the `ruff` plugin is installed? I'm surprised that it doesn't show our official Ruff logo.

**Comment by pitosalas** [comment]
Assuming that’s the correct version number…

**Comment by pitosalas** [comment]
I just uninstalled and reinstalled and got a later one. However I still
can’t invoke it nor does is show up when I try to choose a new
default formatter…

Pito

**Comment by MichaReiser** [comment]
> Assuming that’s the correct version number…

What's the version number?
