### ISSUE TITLE
The ruff VSCode extension doesn't appear to function in a particular VSCode dev-extension environment (works in "default" environment)

### ISSUE THREAD

**Issue by wolfch-elsevier** [astral-sh/ruff-vscode#432]
Here's a simple piece of contrived code:
```python
from requests import ReadTimeout, Request, Response, Timeout, TooManyRedirects
from sys import argv
import logging
import os

def main() -> None:
    pass
```
In the first case, I wanted the extension to perform the equivalent of `isort`, so in VSCode, I invoke `Shift-Command-P` (MacOs) and from the list:
`Ruff: Format Imports`
...nothing happens - the code doesn't change.

Then, from the command line, I invoke:
`ruff check --fix --select I roughruff.py`
...where `roughtruff.py` is the quoted code above and this time, it gets changed to:
```python
import logging
import os
from sys import argv

from requests import ReadTimeout, Request, Response, Timeout, TooManyRedirects


def main() -> None:
    pass
```
So `ruff` can successfully replace `isort` but only via the command line - the VSCode extension doesn't work.

**Comment by charliermarsh** [comment]
Can you share any relevant logging from VS Code? There isn't much to go off in the write-up above. I'm referring to this pane:

![Screenshot 2024-03-16 at 10 17 28 AM](https://github.com/astral-sh/ruff-vscode/assets/1309177/994b0bfe-4176-43dc-99c7-671e6c2ee569)

You should be able to access it by clicking "Ruff" here from a Python file, though it may vary based on how your VS Code is configured:

![Screenshot 2024-03-16 at 10 17 24 AM](https://github.com/astral-sh/ruff-vscode/assets/1309177/0a2e6bc1-d7c2-4e57-9fa6-7aca747de2ad)

**Comment by wolfch-elsevier** [comment]
Wow - thanks for the timely reply!  I look at the bottom strip and only see:
<img width="1316" alt="Screenshot 2024-03-22 at 12 47 55 AM" src="https://github.com/astral-sh/ruff-vscode/assets/57952821/56cebe87-de07-402d-9ea9-e900988225d4">

I don't see "Ruff"; I do see a warning, "Select Interpreter" but when invoke `Shift-Command-P`, it shows the "Selected Interpeter" to be:
<img width="828" alt="Screenshot 2024-03-22 at 12 48 46 AM" src="https://github.com/astral-sh/ruff-vscode/assets/57952821/54385723-5542-4f7a-8dd7-0f890bdc1dfa">
...which is correct.  I should mention this is running inside of a dev-container (sorry, I should have made that clear initially)

**Comment by charliermarsh** [comment]
Could you try opening the log file from the command palette instead, like this?

![Screenshot 2024-03-22 at 12 56 59 AM](https://github.com/astral-sh/ruff-vscode/assets/1309177/c136fc83-97f4-4d7d-b6b6-e0530fbb9eaf)

![Screenshot 2024-03-22 at 12 57 01 AM](https://github.com/astral-sh/ruff-vscode/assets/1309177/acf8e1a0-de8c-4e95-9afd-e567b854a3b4)

**Comment by wolfch-elsevier** [comment]
Wait - I needed to select "Ruff" from the "Output" drop-down
<img width="1020" alt="Screenshot 2024-03-22 at 12 58 16 AM" src="https://github.com/astral-sh/ruff-vscode/assets/57952821/c439ee1c-c643-4966-b656-b75412632891">

**Comment by wolfch-elsevier** [comment]
I re-tried "Select Interpreter" which select the `default` (not correct in terms of installed dependencies) but this tine the Ruff VSCode extension works - see the attached log.
[ruff.log](https://github.com/astral-sh/ruff-vscode/files/14717571/ruff.log)

but I expected it to work with the selected [hatch](https://hatch.pypa.io/1.9/environment/) environment.  Let me change the title of this issue - and offer my apologies.. this dev-container concept is a bit difficult.

**Comment by wolfch-elsevier** [comment]
Oh God - it totally works in the dev-container - **sorry!**.    _**However**_:  I have some caveats for people looking to use this extension in a VSCode [dev-container](https://code.visualstudio.com/docs/devcontainers/containers).  If you have a [monorepo](https://en.wikipedia.org/wiki/Monorepo) with each service having a corresponding [hatch environemtn](https://hatch.pypa.io/1.9/environment/) other than `default`, you need to insure that the [ruff](https://github.com/astral-sh/ruffl) dependency is declared and installed in the particular [hatch environemtn](https://hatch.pypa.io/1.9/environment/) you are using.

**Comment by wolfch-elsevier** [comment]
The use-case was specific to using within a [dev-container](https://code.visualstudio.com/docs/devcontainers/containers) which lead to the false belief it was not working.

**Comment by charliermarsh** [comment]
Glad to see it resolved, sorry you ran into trouble!
