### ISSUE TITLE
Environment variables are not expanded in "ruff.path" VSCode settings

### ISSUE THREAD

**Issue by erjac77** [astral-sh/ruff-vscode#448]
Ruff: 0.3.7
VSCode: 1.88.0
OS: Ubuntu 22.04
Python: 3.11.8

If I specify a path to a custom ruff executable containing environment variables:

```json
"ruff.path": [
  "${workspaceFolder}/dist/export/python/virtualenvs/ruff/${env:PYTHON_VERSION}/bin/ruff"
]
```

I get the following error message:

```bash
Interpreter executable (/workspace/dist/export/python/virtualenvs/ruff/${env:PYTHON_VERSION}/bin/ruff) not found
```

Seems like [predefined variables](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) are expanded, but not the [environment variables](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables).

Related to https://github.com/astral-sh/ruff-vscode/issues/413.

Thank you.

**Comment by dhruvmanila** [comment]
I'm unsure where VS Code retrieves the environment variables from. Is it possible that the environment variable isn't defined in the environment where VS Code is launched? Could you try opening VS Code via the shell in which the environment variable is defined (like `code .`)?

**Comment by dhruvmanila** [comment]
Ok, that actually doesn't work either.

**Comment by dhruvmanila** [comment]
I looked into this a bit more and it seems that the extension only substitutes certain variables which I assume is just a side effect of inheriting from the [Python extension template](https://github.com/microsoft/vscode-python-tools-extension-template/blob/d0b6a8cde1fa75ef6b4325f979aca7508f81a063/src/common/settings.ts#L22-L42):

https://github.com/astral-sh/ruff-vscode/blob/332b4def4fed463cc176f6371a970245f0f612e4/src/common/settings.ts#L59-L79

**Comment by erjac77** [comment]
Sorry for the late response. Just to confirm that your PR seems to fix this issue. Thank you.
