### ISSUE TITLE
Better documentation (import sorting)

### ISSUE THREAD

**Issue by danielniccoli** [astral-sh/ruff-vscode#449]
I've been trying to get import sorting working.

There is one settings-sample that shows this:

![grafik](https://github.com/astral-sh/ruff-vscode/assets/2971735/74706ca2-e2e7-4bd2-8608-f6ab2a91d9bb)

Looking into the default settings, I found this

![grafik](https://github.com/astral-sh/ruff-vscode/assets/2971735/6012c6f1-19b0-479c-836a-329e2a1a32a2)

The way I first understood it was, that the setting from the first screenshot is already set by default. It took me some research to understand that the first setting by default only allows the setting from the second screenshot to be enabled in the first place. And I still had to explicitly set `"source.organizeImports": "explicit"`.

I find this confusing, because I expected the first table to be a comprehensive list of possible settings. But the table shows only half of what's possible and the samples add the rest. That settings for different stuff have the same name's adds to the confusion. I also found the samples a bit confusing, because it doesn't really explain why a certain configuration is achieved with a certain set of settings.

What I think would improve this, is a comprehensive list of all settings and what they do.

**Comment by dhruvmanila** [comment]
> I've been trying to get import sorting working.

Can you expand on what you're trying to achieve?

> I find this confusing, because I expected the first table to be a comprehensive list of possible settings. But the table shows only half of what's possible and the samples add the rest. That settings for different stuff have the same name's adds to the confusion. I also found the samples a bit confusing, because it doesn't really explain why a certain configuration is achieved with a certain set of settings.

Correct me if I'm wrong but I think there's some confusion here. Assuming that the table you're mentioning is [this](https://github.com/astral-sh/ruff-vscode#settings), the table only lists the VS Code settings that the _extension_ provides while the sample shows how you can configure the VS Code _editor_ for common scenarios. This means that the settings shown in the samples are all part of the editor and not the extension. For a comprehensive list of settings that the editor provides, you might want to refer to their [documentation](https://code.visualstudio.com/docs/getstarted/settings).

I guess the confusion is coming from the fact that both the extension and the editor provides a setting where "organizeImports" is being used while both have a different meaning.

**Comment by dhruvmanila** [comment]
We've added https://docs.astral.sh/ruff/editors/settings/ which I think should help here.

**Comment by dhruvmanila** [comment]
I'll mark this as resolved but feel free to provide additional suggestions that you may have.
