### ISSUE TITLE
Ruff version mismatch

### ISSUE THREAD

**Issue by lociii** [astral-sh/ruff-vscode#464]
[Repository on GitHub](https://github.com/astral-sh/ruff-vscode/blob/main/pyproject.toml#L13) lists `0.4.1` as a dependency, however the extension downloadable from the [marketplace](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff) ships with `0.4.2`.

This makes it pretty unpredictable to keep the ruff version in sync with other tools (like pre-commit or build pipelines).

**Comment by dhruvmanila** [comment]
Interesting! I think that's the pre-release version you're looking at. The release version does ship with `0.4.1` Ruff version. I'm not sure how to switch the linked page to show the latest release version instead.

<img width="1252" alt="Screenshot 2024-05-15 at 13 24 03" src="https://github.com/astral-sh/ruff-vscode/assets/67177269/237305db-5833-4251-8741-77411b12efe6">

You can see it in the `pre-release` branch that the Ruff version is `0.4.2`:
https://github.com/astral-sh/ruff-vscode/blob/4c4730a482d47b5499d5f7e31897264fdc181304/pyproject.toml#L13

**Comment by lociii** [comment]
Interesting. Thanks for the clarification.
This is very confusing as there is no way to find out about production or pre-release on that marketplace page.

**Comment by dhruvmanila** [comment]
Yeah, I think the page uses the latest version. The way the different versions work is that even numbers are used for stable versions and odd numbers are used for pre-release versions. So, the latest version will always be the pre-release version.

I'm not sure we can do anything here :(

**Comment by charliermarsh** [comment]
The good news is that they'll be unified soon (the versions will be the same across pre-release and stable).

**Comment by charliermarsh** [comment]
These are now aligned.
