### ISSUE TITLE
Tracking issues that could be closed by new `ruff server`

### ISSUE THREAD

**Issue by T-256** [astral-sh/ruff-vscode#480]
### Unexpected when `ruff.nativeServer` enabled
- [x] #154
- [ ] #240 (Requires #479)
- [x] #281
- [x] #425

### Already solved
- [x] #313
- [x] #408
- [x] #440
- [x] #464

### Outdated
- [x] #40
- [x] #417
- [x] #430
- [x] #465

### Upstream
- [ ] #128

**Comment by charliermarsh** [comment]
Thank you!
