### ISSUE TITLE
Does Ruff extension offer on-hover introspection?

### ISSUE THREAD

**Issue by alexandreczg** [astral-sh/ruff-vscode#492]
Hi,

I'm coming from the Pylance world and trying the Ruff language server. I just installed it on my vscode and wondering about if the on-hover introspection is offered? 

Like in this screenshot:

![image](https://github.com/astral-sh/ruff-vscode/assets/131292734/95eb9bf9-af9d-43d9-a93e-3ccbf40d8dac)

The above is coming from Pylance. I was wondering if we still need both extensions? If I remove Pylance I don't get any introspection. 

Thank you,

- Ruff Version: 0.4.8
- Extension Version: v2024.26.0

**Comment by charliermarsh** [comment]
Yeah, the Ruff LSP is intended to be used alongside a "full" LSP like Pylance. The Ruff LSP offers linting, quick fix, and formatting capabilities, but it is not a general LSP (i.e., it doesn't do Go-To Completion or similar).

**Comment by alexandreczg** [comment]
@charliermarsh Thank you!

I spent 2 hours trying to disable the extra extensions (ms-python.python, ms-python.vscode-pylance, etc) being installed, now I understand why it wasn't working 🤣 

Quick follow-up. Is there a way to only have the linting coming from Ruff, and remove the LSP (Pylance) ?

![image](https://github.com/astral-sh/ruff-vscode/assets/131292734/281f9cf7-d772-48c1-b8d7-b8bc7337f388)

**Comment by charliermarsh** [comment]
Oh no! I'm sorry for the trouble. When in doubt you can always ask.

Yeah, you can configure Pylance to stop showing those. There's some code [here](https://github.com/astral-sh/ruff-vscode/issues/133#issuecomment-1564491340) and [here](https://github.com/astral-sh/ruff-vscode/issues/133#issuecomment-1455085053) demonstrating how to configure it.
