### ISSUE TITLE
Linux-64 installer is missing

### ISSUE THREAD

**Issue by GuilleAmutio** [astral-sh/ruff-vscode#499]
Hello Team,

We are so happy with Ruff and our users too, we are trying to enforce the use of it, so thank you very much for the work you are doing!

The issue i am encountering right now is regarding to the installers available from OpenVSX. We have our own marketplace so we are repsonsible of updating it through some scripts that will look for the linux-64 installer. This is the OpenVSX reference https://open-vsx.org/extension/charliermarsh/ruff

This script was **working until version 2024.22.0** but **2024.24.0 and 2024.26.0 fails saying there is no linux-64 installer**.

I would like to ask if this installer is not plan to come with newer versions or could it be included?

Thank you very much

**Comment by zanieb** [comment]
Hi! Thanks for the kind words.

It looks like the OpenVSX publish failed for 2024.26.0 (we'll look into that!) but it succeeded for 2024.24.0, are you sure it's not working for both on your end? The VSX listing you linked to shows a Linux-64 build for 2024.24.0 but it **is** missing for 2024.26.0.

**Comment by GuilleAmutio** [comment]
My bad, 2024.24.0 is working, but thank you for noting the issue with 2024.26.0

**Comment by zanieb** [comment]
We did a new release and it looks like everything published. Thanks!
