### ISSUE TITLE
Native sever should not rely python 

### ISSUE THREAD

**Issue by karthiknadig** [astral-sh/ruff-vscode#503]
Ruff with native server should not use python to run:
![image](https://github.com/astral-sh/ruff-vscode/assets/3840081/bac66c70-113e-473a-99d5-44c0c6d7f4ce)

If `ruff` needs python path it should be passed in via either `initializationOptions` or with workspace configuration change.

**Comment by MichaReiser** [comment]
That makes sense. There's currently one python left and we should try to rewrite it to Typescript to cap the Python dependency. See https://github.com/astral-sh/ruff-vscode/issues/479

**Comment by charliermarsh** [comment]
That's the only reason we rely on Python. We need to introspect `sysconfig`.
