### ISSUE TITLE
Graceful notification for unsupported features.

### ISSUE THREAD

**Issue by T-256** [astral-sh/ruff-vscode#508]
Since the default behavior of this extension is to use ruff binary from environment, sometimes users update the extension but still use outdated version of ruff binary in their environment.
So, when new feature available to the extension's settings/commands, it may throw multiple error notifications to the users about ruff crashing.
potential solution is specifying minimum required ruff version at extension side for new settings/commands. so, when that feature has been used, we can ignore it and show user a warning instead.

**Comment by dhruvmanila** [comment]
Is this similar to https://github.com/astral-sh/ruff-vscode/issues/476?
