### ISSUE TITLE
Support organizing imports in jupyter cells

### ISSUE THREAD

**Issue by guyrosin** [astral-sh/ruff-vscode#51]
The "Organize Imports" action of the isort vscode extension works for jupyter cells while ruff's Organize Imports does nothing when attempting to run in a cell.

**Comment by charliermarsh** [comment]
Cool, I'm sure we can support this but I have to look into how it's done.

**Comment by blakeNaccarato** [comment]
The team over at microsoft/vscode-black-formatter are [blocked by pygls still being on LSP v3.16]. Looks like @charliermarsh you are too. The closest related issue over at `pygls` is https://github.com/openlawlibrary/pygls/issues/311. Once `pygls` supports LSP 3.17 (it's on 3.16 now), all language server protocol implementations depending on `pygls` should be able to parse notebooks as whole documents!

**Comment by thoughtfuldata** [comment]
@guyrosin  organize imports doesnt work for me, how did you get it to work for you?

**Comment by guyrosin** [comment]
If you install the [isort vscode extension](https://marketplace.visualstudio.com/items?itemName=ms-python.isort) you can use its Organize Imports action

**Comment by thoughtfuldata** [comment]
exactly what I did, but its the isort extension doing the work. when I choose ruff it doesnt do anything

**Comment by guyrosin** [comment]
Yep, that's what this issue is all about :)

**Comment by juanfcocontreras** [comment]
I think this information (new VSCode release) could be relevant to this issue:

> [Code Actions on save](https://code.visualstudio.com/updates/v1_79#_code-actions-on-save)
>
> Notebooks now support Code Actions being run upon save. Code Actions can be specified under the notebook.codeActionsOnSave setting. Extension authors can define providers using the standard typings for cell level Code Actions, or use the new notebook. prefix to define Code Actions that manage the entire notebook. You can review the [clean-nb-imports-ext](https://github.com/Yoyokrazy/clean-nb-imports-ext) sample extension to learn how extensions can use this new setting.

**Comment by alexclaydon** [comment]
We'd love to see this too - we're keeping isort around just for this atm.

**Comment by charliermarsh** [comment]
We very much want to add this, but we're waiting on support from the library we use for our LSP server (pygls). See: https://github.com/openlawlibrary/pygls/issues/311.

**Comment by jtele2** [comment]
I see this has been marked as closed but how do we sort imports on save with `isort` in a VS Code Notebook?

**Comment by charliermarsh** [comment]
This used to work, but I think something regressed in VS Code. We filed an issue: https://github.com/microsoft/vscode/issues/216653.

**Comment by memeplex** [comment]
Shouldn't this be reopened since it's not working? Even if it's waiting for some fix upstream.

**Comment by memeplex** [comment]
Btw, as a workaround I'm using the "Ruff: format imports" command.

**Comment by dhruvmanila** [comment]
To summarize, this `Organize Imports` command used to work earlier but something broke in upstream (https://github.com/microsoft/vscode/issues/216653) which led to this stopped working.

**Workarounds:**
1. Use the `Ruff: Format Imports` command from the command palette
2. To automatically sort imports on save, use the following config:
    ```json
    {
      "notebook.codeActionsOnSave": {
        "notebook.source.organizeImports": "explicit"
      }
    }
    ```
