### ISSUE TITLE
How to find out what config file ruff discovered?

### ISSUE THREAD

**Issue by parthmishra** [astral-sh/ruff-vscode#534]
Is there a way to see what configuration file the Ruff extension is using in the project? When using the cli, I can see this with `--verbose` but that's not supported in the extension. 

My current issue is that I don't why the CLI can pick up the correct `pyproject.toml` in the root of the repo but the extension can't, but in general I'd like to know how I can debug these issues myself. 

Current workspace settings: 
```json
{
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.codeActionsOnSave": {
            "source.fixAll.ruff": "explicit",
            "source.organizeImports.ruff": "explicit"
        }    
    },
}
```

All user settings are default.

**Comment by dhruvmanila** [comment]
It depends on which backend server are you using? Is it `ruff-lsp` or the native server? Do you have the `ruff.nativeServer` setting set in VS Code?

**Comment by parthmishra** [comment]
> It depends on which backend server are you using? Is it `ruff-lsp` or the native server? Do you have the `ruff.nativeServer` setting set in VS Code?

Using the normal LSP (whichever is default)

**Comment by dhruvmanila** [comment]
Can you checkout the [Troubleshooting](https://github.com/astral-sh/ruff-vscode#troubleshooting) guide and see if that helps?
