### ISSUE TITLE
[Bug] Path Handling Issue in VS Code Ruff Plugin with Spaces in Path

### ISSUE THREAD

**Issue by YlguYtrid** [astral-sh/ruff-vscode#541]
After updating the VS Code Ruff plugin to version 2024.32.0, I encountered an issue where the plugin fails to find the Ruff binary when the path contains spaces. The error message suggests that the path is being split into two parts, causing the command to fail. This issue did not exist in the previous version of the plugin.

Error Message:
```vbnet
[error] Error while trying to find the Ruff binary: Error: Command failed: d:\LeetCodeSolutions\.venv\Scripts\python.exe c:\Users\Ylgu Ytrid\.vscode\extensions\charliermarsh.ruff-2024.32.0-win32-x64\bundled\tool\find_ruff_binary_path.py
C:\Users\Ylgu Ytrid\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'c:\\Users\\Ylgu': [Errno 2] No such file or directory
```

**Comment by MichaReiser** [comment]
I'm sorry you're running into this. I think this should be fixed with https://github.com/astral-sh/ruff/issues/12394 However, it seems that it was only released as a pre-release. Let me double check why this is.

**Comment by MichaReiser** [comment]
I'm prepping a stable release https://github.com/astral-sh/ruff-vscode/pull/542
