### ISSUE TITLE
There is a configuration conflict between the ruff.lint.extendSelect and ruff.format.args settings.

### ISSUE THREAD

**Issue by gfourdx** [astral-sh/ruff-vscode#569]
vscode settings.sjon: 

```json
{
    "python.defaultInterpreterPath": "/home/toor/venvs/dispatch-api/bin/python3",
    "python.languageServer": "Pylance",
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000,
    "terminal.integrated.tabs.enabled": true,
    "explorer.autoReveal": true,
    "editor.fontSize": 14,
    "editor.guides.bracketPairs": true,
    "outline.showVariables": false,
    "editor.formatOnSave": true,

    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.codeActionsOnSave": {
        "source.organizeImports.ruff": "explicit",
        "source.fixAll.ruff": "explicit",
    },

    "ruff.lineLength": 88,
    "ruff.lint.select": ["E", "F", "W", "Q", "UP", "I", "N"],
    "ruff.lint.extendSelect": ["TCH"],
    "ruff.format.args": ["--config", "format.quote-style='preserve'"],
}
```

vscode verion: v1.92.0
ruff extension version:  v2024.36.0
environment: wsl2(Debian)
python: 3.9.2

I have enabled the setting "ruff.format.args": ["--config", "format.quote-style='preserve'"]
The configuration "ruff.lint.extendSelect": ["TCH"] will become ineffective

If the "ruff.format.args": ["--config", "format.quote-style='preserve'"] is commented out
then "ruff.lint.extendSelect": ["TCH"] will become effective
as shown in the image below:
![image](https://github.com/user-attachments/assets/eccc7340-d580-4728-bac6-2cddb28d3a1a)

**Comment by dhruvmanila** [comment]
Yes, that is expected. For context,

[`ruff.format.args`](https://docs.astral.sh/ruff/editors/settings/#formatargs) is going to be deprecated and is not read by the native server as mentioned in the documentation for that setting:

<img width="684" alt="Screenshot 2024-08-02 at 15 35 16" src="https://github.com/user-attachments/assets/b66207ce-3c59-4e4e-8a80-3853d41ffab7">

While, [`ruff.lint.extendSelect`](https://docs.astral.sh/ruff/editors/settings/#extendselect) is a new setting which is only relevant when the native server is being used (`ruff.nativeServer` is `"on"`) and is also mentioned in the documentation:

<img width="562" alt="Screenshot 2024-08-02 at 15 35 32" src="https://github.com/user-attachments/assets/5eba9a3f-0481-4c02-8563-049c7c7a51bf">

In your config, the following settings are only relevant to the native server:
```json
"ruff.lineLength": 88,
"ruff.lint.select": ["E", "F", "W", "Q", "UP", "I", "N"],
"ruff.lint.extendSelect": ["TCH"],
```

But, as you have set the [`ruff.format.args`](https://docs.astral.sh/ruff/editors/settings/#formatargs) setting, the extension will use the old server (`ruff-lsp`) which doesn't know about the above settings.

Currently, to migrate this config, you'd need to include the formatter setting in your local config file. If you want to use a common config for all your projects in an editor, you can use the [`ruff.configuration`](https://docs.astral.sh/ruff/editors/settings#configuration) option.

Does this help? Feel free to ask any other questions that you might have.

**Comment by T-256** [comment]
Same as https://github.com/astral-sh/ruff/issues/11228, I think makes sense to have native options for these settings.
Since [it's not possible](https://github.com/astral-sh/ruff-vscode/issues/260#issuecomment-2246824420) to implement single exclusive settings, we should consider adding them one by one.

**Comment by gfourdx** [comment]
> Yes, that is expected. For context,
> 
> [`ruff.format.args`](https://docs.astral.sh/ruff/editors/settings/#formatargs) is going to be deprecated and is not read by the native server as mentioned in the documentation for that setting:
> 
> <img alt="Screenshot 2024-08-02 at 15 35 16" width="684" src="https://private-user-images.githubusercontent.com/67177269/354558014-b66207ce-3c59-4e4e-8a80-3853d41ffab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjcyOTksIm5iZiI6MTcyMjgyNjk5OSwicGF0aCI6Ii82NzE3NzI2OS8zNTQ1NTgwMTQtYjY2MjA3Y2UtM2M1OS00ZTRlLThhODAtMzg1M2Q0MWZmYWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAzMDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYzAzZmU2MTc3MjFlOGU3Y2QwYmQwZWRkYjk5ZTI5Nzg4MzY0NzExNjc4ZmY4MmEwM2I2N2IwYWRlYmQ3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbZbjadJBgsU6QDNVxBagRZlCWTrKekin6Xi7WNvfDQ">
> While, [`ruff.lint.extendSelect`](https://docs.astral.sh/ruff/editors/settings/#extendselect) is a new setting which is only relevant when the native server is being used (`ruff.nativeServer` is `"on"`) and is also mentioned in the documentation:
> 
> <img alt="Screenshot 2024-08-02 at 15 35 32" width="562" src="https://private-user-images.githubusercontent.com/67177269/354558094-5eba9a3f-0481-4c02-8563-049c7c7a51bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjcyOTksIm5iZiI6MTcyMjgyNjk5OSwicGF0aCI6Ii82NzE3NzI2OS8zNTQ1NTgwOTQtNWViYTlhM2YtMDQ4MS00YzAyLTg1NjMtMDQ5YzdjN2E1MWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAzMDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYWJkZWNmZWNmZDlhOWM1NzI0OTE1NjI4ZTA5ZDY2Y2E4ZGIyYWQ0MjBiODVhOWYyODgzMDJiNWY5ZWQxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6IpB1S0YA-S2Ls4z4tzl-UPw6cFCK8WLGuCqXBWllJ0">
> In your config, the following settings are only relevant to the native server:
> 
> ```json
> "ruff.lineLength": 88,
> "ruff.lint.select": ["E", "F", "W", "Q", "UP", "I", "N"],
> "ruff.lint.extendSelect": ["TCH"],
> ```
> 
> But, as you have set the [`ruff.format.args`](https://docs.astral.sh/ruff/editors/settings/#formatargs) setting, the extension will use the old server (`ruff-lsp`) which doesn't know about the above settings.
> 
> Currently, to migrate this config, you'd need to include the formatter setting in your local config file. If you want to use a common config for all your projects in an editor, you can use the [`ruff.configuration`](https://docs.astral.sh/ruff/editors/settings#configuration) option.
> 
> Does this help? Feel free to ask any other questions that you might have.

thank you
