### ISSUE TITLE
formatOnSave not working on notebook

### ISSUE THREAD

**Issue by JordanHeintz** [astral-sh/ruff-vscode#571]
### Description
As far as I can tell, I have applied the necessary configuration to use Ruff to format notebooks on save, but it just will not do anything. It does work on regular python files just fine.

### Environment
Windows 10
Python: 3.12.4
VSCode Ruff Extension: v2024.36.0 (includes ruff 0.5.4)

I have the following in my settings.json:
```
{
    "notebook.formatOnSave.enabled": true,
    "notebook.defaultFormatter": "charliermarsh.ruff",
    "notebook.codeActionsOnSave": {
        "notebook.source.fixAll": "explicit",
        "notebook.source.organizeImports": "explicit",
    },
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.codeActionsOnSave": {
            "source.fixAll": "explicit",
            "source.organizeImports": "explicit",
        }
    },
}
```
I added a ruff.toml file to my workspace with the following setting:
```
[tool.ruff]
extend-include = ["*.ipynb"]
```
IIUC, the extension should find that file automatically, but I also tried specifying a path to ruff.toml in the extension settings, with no effect.

### Expected Results
I expected Ruff to format my .ipynb files on save the same it does my .py files.

### Actual Results
Nothing. VSCode Output shows the extension loading, resolving `ruff.nativeServer: auto` to use the native server, and a request to start the server, with no indications that any errors occur.

**Comment by dhruvmanila** [comment]
It could be that there are multiple formatters available for Python files. Can you try running the "Notebook: Format Notebook" command verify whether that works? Does VS Code provide a dialog like the following?

<img width="315" alt="Screenshot 2024-08-06 at 12 16 51" src="https://github.com/user-attachments/assets/f77deb4c-7a40-47eb-9663-8036ef70a47e">

If so, you'd need to configure a default formatter for Python files:
```json
{
  "[python]": {
    "editor.defaultFormatter": "charliermarsh.ruff",
  }
}
```

**Comment by JordanHeintz** [comment]
I don't seem to have a "Notebook: Format Notebook" command in my command palette. However, that is an option in the right-click menu when I have a notebook open, and it doesn't seem to do anything.

I do already have "editor.defaultFormatter" set in the code block I posted above. Did I do something wrong there?

**Comment by MichaReiser** [comment]
Strange. Does formatting regular python files work as expected?

**Comment by JordanHeintz** [comment]
Yes, formatting regular Python files works perfectly.

**Comment by dhruvmanila** [comment]
> I added a ruff.toml file to my workspace with the following setting:

Do you have any other config in your workspace? For instance, is there a `pyproject.toml` as well with `[tool.ruff]` section in it?

> I don't seem to have a "Notebook: Format Notebook" command in my command palette.

This command will only be available when a Jupyter Notebook is opened in the editor.

So, your config looks correct to me and it's working fine on my machine.

**Comment by msongtw** [comment]
I too am having this issue with the Ruff native server but not with ruff-lsp.

**Comment by JordanHeintz** [comment]
> Do you have any other config in your workspace? For instance, is there a pyproject.toml as well with [tool.ruff] section in it? If it's there, can you make sure there's only one config (either pyproject.toml or ruff.toml)?

Nope, no other configs in that workspace.

> This command will only be available when a Jupyter Notebook is opened in the editor.

Ah, thanks for that tip. No, that command doesn't seem to do anything either.

**Comment by dhruvmanila** [comment]
Oh ok, I see the problem. The `ruff.toml` file does not need the `[tool.ruff]` header, it's only required in `pyproject.toml` file. You can see that we provide examples for how a setting should be added in both files at https://docs.astral.sh/ruff/settings/. So, if your file is `ruff.toml`, then it should just be:
```toml
extend-include = ["*.ipynb"]
```

Can you try this?

**Comment by JordanHeintz** [comment]
Yep, that was it, thank you. I must've read through that doc a half dozen times, and I missed that detail each time, sorry! Appreciate the responsiveness!
