### ISSUE TITLE
Package.json: enum types need a description

### ISSUE THREAD

**Issue by karthiknadig** [astral-sh/ruff-vscode#581]
There is no description for these options:
![image](https://github.com/user-attachments/assets/750048e7-8439-4674-aa64-03e8ceed3219)

See https://github.com/astral-sh/ruff-vscode/blob/d84e14b6326b28997920bbc23f5a89b983f0effc/package.json#L236-L239 for examples

You can use `markdownEnumDescriptions` for even richer descriptions

**Comment by dhruvmanila** [comment]
They're there:

https://github.com/astral-sh/ruff-vscode/blob/d84e14b6326b28997920bbc23f5a89b983f0effc/package.json#L94-L100

Not sure why it's not rendering for you:

<img width="813" alt="Screenshot 2024-08-09 at 23 00 29" src="https://github.com/user-attachments/assets/3a3698bf-9238-48a2-805d-ad8b0a109ae1">

**Comment by karthiknadig** [comment]
Sorry about this, looks like I needed to just reload.
