### ISSUE TITLE
VSCode ruff extension NOT formatting Notebooks (windows?!)

### ISSUE THREAD

**Issue by Julian-J-S** [astral-sh/ruff-vscode#582]
I regularly experience problems with the VSCode ruff extension on windows where it does NOT format notebook files (.ipynb).

Super easy example (probably not reproducable for most but happens to me all the time)
Notebook (`format_me.ipynb`) with a single code cell)
```python
print(         "Hello, World!"            )
```
Result: nothing happens

Format Invocation:
- VSCode Extension
![image](https://github.com/user-attachments/assets/a975d322-86b7-4f1c-9496-26c489fe6779)

Additional Info:
- only notebook affected; same code as ".py" works
- exact same notebook formats on MacOS! (not working on windows; might be something else but noteworthy)
- no ruff cli installed. Only the extension; vscode extensin: v2024.40.0

Atteched ipynb file as json because attaching ipynb extension not possible :D 

[format_me.json](https://github.com/user-attachments/files/16578772/format_me.json)

**Comment by Julian-J-S** [comment]
You are right. I was missing the `extend-include = ["*.ipynb"]`
I could swear this worked on my Mac without that at some point 😆

**Comment by dhruvmanila** [comment]
> You are right. I was missing the `extend-include = ["*.ipynb"]` I could swear this worked on my Mac without that at some point 😆

Yes, it works without any configuration when using the [Python based language server](https://github.com/astral-sh/ruff-lsp) but it doesn't with the native server (`ruff.nativeServer: "on"`). This has changed with the latest minor release where Jupyter Notebooks are linted and formatted by default: https://astral.sh/blog/ruff-v0.6.0#jupyter-notebooks-are-now-linted-and-formatted-by-default.
