### ISSUE TITLE
Extension breaks on Windows if Ruff binary file path contains non-ASCII characters

### ISSUE THREAD

**Issue by floxay** [astral-sh/ruff-vscode#583]
There are actually two issues on Windows:
1) https://github.com/astral-sh/ruff-vscode/blob/main/bundled/tool/find_ruff_binary_path.py fails if it encounters a character not supported by Windows-1252 (cp1252), let's say if I have a directory called `löカひ漢` it will fail with the trace below;
	<details>
	<summary>Python Trace:</summary>

	```py
	2024-08-15 13:59:10.579 [info] Using interpreter: c:\löカひ漢\.venv\Scripts\python.exe
	2024-08-15 13:59:10.735 [error] Error while trying to find the Ruff binary: Error: Traceback (most recent call last):
	  File "c:\Users\user\.vscode\extensions\charliermarsh.ruff-2024.40.0-win32-x64\bundled\tool\find_ruff_binary_path.py", line 35, in <module>
	    print(os.fsdecode(str(ruff_binary_path)), flush=True)
	  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 19, in encode
	    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-7: character maps to <undefined>
	```
	</details>
2) Non-ASCII characters which are part of Windows-1252 prevent the extension from using the Ruff binary, the extension will be stuck in a "loading" phase;
	```py
	2024-08-15 14:10:49.461 [info] Using interpreter: c:\lö\.venv\Scripts\python.exe
	2024-08-15 14:10:49.585 [info] Using the Ruff binary: c:\l�\.venv\Scripts\ruff.exe
	```
	Relevant line and function: https://github.com/astral-sh/ruff-vscode/blob/d84e14b6326b28997920bbc23f5a89b983f0effc/src/common/server.ts#L129

**Comment by MichaReiser** [comment]
Thanks. I can reproduce this. The bug is in `find_ruff_binary_path.py` and only happens if there's a ruff binary in the venv. The error doesn't arise if the venv does not contain a ruff binary. 

To unblock you, you can specify `ruff.path`  and set it to `C:\löカひ漢\.venv\Scripts\ruff.exe`.

**Comment by MichaReiser** [comment]
Okay, I have a solution for this. The problem is Python's default choice of stdio encoding:

> On Windows, UTF-8 is used for the console device. Non-character devices such as disk files and pipes use the system locale encoding (i.e. the ANSI codepage). Non-console character devices such as NUL (i.e. where isatty() returns True) use the value of the console input and output codepages at startup, respectively for stdin and stdout/stderr. This defaults to the system [locale encoding](https://docs.python.org/3/glossary.html#term-locale-encoding) if the process is not initially attached to a console.

[source](https://docs.python.org/3/library/sys.html#sys.stdout)

Which seems silly to me but eh... We should reconfigure to UTF8 which is what node expects
