### ISSUE TITLE
source.fixall formats but does not fix all issues

### ISSUE THREAD

**Issue by eugenenelou** [astral-sh/ruff-vscode#589]
Hey, I have some rules with autofix available  that are correctly fixed when running the command `Ruff: Fix all auto-fixable problems`, but they are not fixed when saving, despite having the settings available to auto-fix on save. 

On save formatting happens, but not autofixing.

here are my settings:

```  
"[python]": {
    "editor.formatOnSave": true,
    "editor.formatOnPaste": false,
    "editor.codeActionsOnSave": {
      "source.organizeImports": "explicit",
      "source.fixall.ruff": "explicit"
    },
    "editor.defaultFormatter": "charliermarsh.ruff"
  },

**Comment by MichaReiser** [comment]
Can you share a code example with the rules that you expect should be fixed when applying fix-all? I wonder if the fixes for those rules are marked as unsafe.

**Comment by eugenenelou** [comment]
Currently it's the `COM812` missing comma rule. the doc says `Fix is always available.`

(I tried setting "unsafe-fixes" to true, but maybe I did it wrong)

**Comment by MichaReiser** [comment]
Thanks. Do you have a code example that you could share? Do you see any output in the `Output: Ruff` tab indicating that there's an error?

**Comment by eugenenelou** [comment]
I have nothing in the output apart from the initial setup that has no error.

example, the trailing comma should appear after `[]`:
```
for obj in list_with_veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery_long_name(
    [1]
):
    print(obj)
```

**Comment by MichaReiser** [comment]
I just tested your code example in VS code and it's working as expected. Could you share your ruff (`pyproject.toml`/`ruff.toml`) configuration with us?

**Comment by eugenenelou** [comment]
Hey, sorry for the delay, here is my config:

```

[tool.ruff.lint]
select = ["ALL"]
# list of rules: https://docs.astral.sh/ruff/rules
ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D106", # Missing docstring in public nested class
    "TRY003", # Avoid specifying long messages outside the exception class
    "ANN101", # Missing type annotation for {name} in method
    "ANN001", # Missing type annotation for function argument {name}
    "ANN002", # Missing type annotation for *{name}
    "ANN003", # Missing type annotation for **{name}
    "ANN201", # Missing return type annotation for public function {name}
    "TD003", # add issue link in # TODO
    "FIX002", # remove TODO comments
]

[tool.ruff]
line-length = 120

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = ["S101", "ARG", "FBT", "D", "PLR2004"]
```

**Comment by dhruvmanila** [comment]
Thanks for providing the config. Running the "Ruff: Fix all auto-fixable problems" command _does_ add the trailing comma after `[1]`. I'm using Ruff 0.5.3, the same version as yours. Can you try it again and verify that the problem persists?

**Comment by eugenenelou** [comment]
Yes it does, my problem is that the `onSave`  doesn't fix it.

**Comment by dhruvmanila** [comment]
Oh ok. I think I see the problem - in your VS Code settings, it should be "fixAll" and not "fixall" (uppercase "A").

**Comment by eugenenelou** [comment]
Oh yes that works! thanks a lot.

**Comment by eugenenelou** [comment]
Oh yes that works! thanks a lot.
