### ISSUE TITLE
VSCode finding wrong versions of Ruff?

### ISSUE THREAD

**Issue by maxiedaniels** [astral-sh/ruff-vscode#595]
Very confused about how Ruff is working right now - I just tried to switch over to the native server in VSCode, and I get an error:
`Native server requires Ruff 0.3.5, but found 0.1.4 at /Users/myusername/.pyenv/shims/ruff instead`

Okay, so I looked up all versions of ruff on my computer. Apparently I have ruff-0.1.4 in a pyenv env using python 3.9, ruff-0.6.1 in the VSCode extensions libs, and then ruff-0.4.8 in a conda python 3.10 env.

In VSCode, when this is happening, I have the Conda env activated, so it *should* be ruff-0.4.8.

So a few questions:
1) Why is it looking at the wrong ruff?
2) Do I need ruff installed in my envs or should i remove those and just have the VSCode extension version?

**Comment by T-256** [comment]
I think your case could be fixed via https://github.com/astral-sh/ruff-vscode/pull/585 (currently WIP).
