### ISSUE TITLE
Ruff sorts already sorted imports on every file save

### ISSUE THREAD

**Issue by AndreiMoraru123** [astral-sh/ruff-vscode#601]
On a long enough list of imports in a file, ruff keeps sorting even though the imports are sorted.

This is important because it messes with the editor's Undo. 
Every undo after a save will bring you back to an artificial state of unsorted imports instead of the state of the code you were trying to undo. 

Demo: With enough saves, writing "aaaa" and then trying to undo it becomes challenging. Only the first save is actually relevant for sorting imports

![ruff](https://github.com/user-attachments/assets/7206cf8d-9179-4351-958f-1a9cb2e302c4)

This happens with the following `settings.json`:

```json
{
  "[python]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll": "explicit",
      "source.organizeImports": "explicit"
    },
    "editor.defaultFormatter": "charliermarsh.ruff"
  }
}
```

This does not seem to happen in a file with a few imports

and does not happen with isort + black.

```json
"ruff.nativeServer": "on",
``` 
does not seem to make a difference

Tried and confirmed on two machines with different projects and environments

**Comment by dhruvmanila** [comment]
This looks annoying. Thanks for reporting.

Before I look into it, I want to clarify a couple of things:

> This is important because it messes with the editor's Undo.
> Every undo after a save will bring you back to an artificial state of unsorted imports instead of the state of the code you were trying to undo.

I'm not exactly sure what do you mean by this. Can you expand a bit to explain how does Ruff extension affects this?

> Demo: With enough saves, writing "aaaa" and then trying to undo it becomes challenging. Only the first save is actually relevant for sorting imports

I'm trying to understand what is exactly happening in the video. What I'm seeing is that the file content bounces between unsorted and sorted imports, is that correct? Is this all done by the Ruff extension? Do you have any other extensions that might sort the imports like the isort extension? Can you try using `"source.organizeImports.ruff"` instead of `"source.organizeImports"` in your VS Code extension to ask the editor to use Ruff's organize imports action?

**Comment by AndreiMoraru123** [comment]
It looks like `source.organizeImports.ruff` magically solved this issue. 

Thanks for this @dhruvmanila!

Could someone add this detail in the vs-code extension highlights?

The "undo mess-up" was an example in case someone would wonder why I would care about such a detail (besides it being annoying).

**Comment by dhruvmanila** [comment]
> It looks like `source.organizeImports.ruff` magically solved this issue.

Yeah, so I think there must be another extension (maybe isort?) installed which also organizes imports and they're conflicting. When using `source.organizeImports`, the client sends it to all the servers that supports it but if you add the `ruff` suffix, it'll only send it to the Ruff server.

**Comment by AndreiMoraru123** [comment]
Yes, I can confirm the problem also gets fixed if I uninstall/disable isort, even though I had nothing set up for isort in `settings.json`

**Comment by dhruvmanila** [comment]
> Yes, I can confirm the problem also gets fixed if I uninstall/disable isort, even though I had nothing set up for isort in `settings.json`

VS Code extensions usually don't require setups, they get activated based on events. For example, the Ruff extension is activated when there are Python files or Jupyter Notebooks in the workspace. It would probably be similar for isort extension as well. The `settings.json` is mainly used to tweak the extension behavior although some extension will provide a way to disable some or all functionalities. And, you can disable an extension entirely from the extension page itself.

I'll mark this issue as resolved.
