### ISSUE TITLE
No hover in VSCode Web Notebooks

### ISSUE THREAD

**Issue by kdzhang** [astral-sh/ruff-vscode#611]
I am using Ruff for vscode-web (SageMaker Code Editor 1.83.1) and Ruff extension version v2024.44.0. The extension works properly for `.py` files, with lint and a hover window showing function signature. But the signature hover does not show up in `.ipynb` files, though the lint does still seem to work. I have added `extend-include = ["*.ipynb"]` in my `pyproject.toml` file. 

with `.py` file
<img width="611" alt="image" src="https://github.com/user-attachments/assets/0b29c113-0729-42ce-af54-38a8be02137c">

with `.ipynb` file, no signature hover, but it could auto-complete argument name if I type a few letters:
<img width="607" alt="image" src="https://github.com/user-attachments/assets/f7813a93-4227-41fc-8f0f-28b381f16fe0">

**Comment by dhruvmanila** [comment]
Ruff doesn't provide hover / signature information for symbols, that must be some other language server. You'd need to install the extension that's providing this information on both environments. It could be the Python extension itself although I'm not sure.

I'll close this issue to keep the issue tracker actionable as it's not related to the Ruff extension.
