### ISSUE TITLE
Undefined name `anext` Ruff(F821)

### ISSUE THREAD

**Issue by AsgeirNoM** [astral-sh/ruff-vscode#616]
* A minimal code snippet that reproduces the bug.
```python
anext
```

* The current Ruff and VS Code settings (any relevant sections from your `pyproject.toml` and `settings.json`).
tuff.toml
```
respect-gitignore = true
```
pyproject.toml
```
[tool.poetry.dependencies]
python = ">=3.11, <3.13"
```

* The current Ruff and VS Code extension versions (`ruff --version`).
`ruff 0.1.15`
VS-Code plugin v2024.48.0

* A description of your environment (e.g., operating system, Python version, etc.).
python3.11.9 / devcontainer mcr.microsoft.com/devcontainers/python:1-3.11-bookworm

![Screenshot_20240911_160343](https://github.com/user-attachments/assets/dadcf129-4bd1-4c84-8857-3ac4cf0614d6)

### Workaround
Turning off ruff as a linter, and only use it for formatting.

**Comment by dhruvmanila** [comment]
Thanks for providing the details. Can you specify what the issue that you're facing here? I'm unable to infer that based on the information that you've provided.

**Comment by AsgeirNoM** [comment]
> Thanks for providing the details. Can you specify what the issue that you're facing here? I'm unable to infer that based on the information that you've provided.

anext is a python3 builtin (since 3.10) https://docs.python.org/3/library/functions.html#anext

**Comment by dhruvmanila** [comment]
> * The current Ruff and VS Code extension versions (`ruff --version`).
>   `ruff 0.1.15`

Can you try it with a recent Ruff version? It doesn't occur in it: https://play.ruff.rs/b6e9c140-0f81-40d3-bfd5-84e80422ff8b

**Comment by arthuriantech** [comment]
Same issue with the latest version. It's really weird thing.
![image](https://github.com/user-attachments/assets/94708709-1928-4787-91ca-27127659351d)

**Comment by MichaReiser** [comment]
> Same issue with the latest version. It's really weird thing.
> 
> ![image](https://github.com/user-attachments/assets/94708709-1928-4787-91ca-27127659351d)
> 
> 

Does your pyproject.toml specify a requires-python or target version?

**Comment by arthuriantech** [comment]
> Does your pyproject.toml specify a requires-python or target version?

Well, specifying `requires-python = ">= 3.12"` solves the issue. Thanks for pointing this out.

**Comment by leonbloy** [comment]
Why was this closed ?
One should not need to specify `requires-python = ">= 3.12"` , if `3.10 ` should suffice.

**Comment by dhruvmanila** [comment]
> One should not need to specify `requires-python = ">= 3.12"` , if `3.10 ` should suffice.

Specifying `>= 3.10` should be ok: https://play.ruff.rs/d4947f48-3e94-4ed5-a47d-f748a294110e
