### ISSUE TITLE
Feature request: format selection 

### ISSUE THREAD

**Issue by daler-rahimov** [astral-sh/ruff-vscode#618]
It would be great to have the option for format selection as well. In large codebases, you often don't want to format the entire document just for formatting purposes. Using the same formatter for both selection-based and full-document formatting ensures consistency across the codebase.

**Comment by MichaReiser** [comment]
Hi @daler-rahimov 

Can you tell me more about what you mean by format selection and what Ruff/extension version you're using. 

Ruff does support range formatting at the statement level (it can't format sub-expressions only). You can also configure VS Code to only format changes

[Screencast from 2024-09-18 09-12-07.webm](https://github.com/user-attachments/assets/22784f49-ab38-49fd-b013-8bc9ce4d4626)

**Comment by daler-rahimov** [comment]
> Hi @daler-rahimov
> 
> Can you tell me more about what you mean by format selection and what Ruff/extension version you're using.
> 
> Ruff does support range formatting at the statement level (it can't format sub-expressions only). You can also configure VS Code to only format changes
> 
>  Screencast.from.2024-09-18.09-12-07.webm

Hello @MichaReiser! I mean exactly what you captured in the screencast. When you select a section of code and try to use "Format Selection" VSCode doesn't seem to use Ruff. I’m guessing it's using Pylance instead. However, if you then run "Ruff: Format Document" the formatting changes.

Example 
original code: 
```python
class SystemMonitorParser:

    def handle( self             ):
        pass
```

format with VSCode "Format Selection"
```python 
class SystemMonitorParser:

    def handle(self):
        pass
```

format with VSCode "Ruff: Format document"
```python
class SystemMonitorParser:
    def handle(self):
        pass
```

**Comment by daler-rahimov** [comment]
Ruff version: `v2024.50.0`

**Comment by MichaReiser** [comment]
Can you try *Format Document With...*. It should then show you a list of available formatters as well as which formatter's the default.  The last option is *Configure Default Formatter* and it allows you to set a default formatter for python (or change it). Let me know if that works for you.

**Comment by daler-rahimov** [comment]
That worked! Configuring Default Formatter did the trick. Thank you!

**Comment by MichaReiser** [comment]
That's great news and thanks for reporting back. 

You might also be interested in [this VS Code setting](https://code.visualstudio.com/updates/v1_49#_only-format-modified-text). You get automatic formatting of changed lines on save.
