### ISSUE TITLE
How to enable autocomplete?

### ISSUE THREAD

**Issue by wkjung** [astral-sh/ruff-vscode#639]
It may sound a dumb question (sorry I'm new). How do I enable autocomplete feature for functions like

![this](https://code.visualstudio.com/assets/docs/python/editing/hello-world.gif)

(grapped from https://code.visualstudio.com/docs/python/editing#_autocomplete-and-intellisense)

I installed ruff extension, enabled native language server, and disabled the default one with `"python.languageServer": "None"`. Still I'm not sure how can I use such 'autocomplete' feature that I am living with pylance. 

Or, does ruff not support that feature? Which means I should live with pylance together with ruff if I want that feature?

**Comment by dhruvmanila** [comment]
Ruff doesn't support auto-completion yet. It's recommended to use another language server for those capabilities. Refer to https://docs.astral.sh/ruff/editors/#language-server-protocol and the features page https://docs.astral.sh/ruff/editors/features/.
