### ISSUE TITLE
Native Server incorrectly formats notebook code with formatOnSave enabled and organizeImports enabled

### ISSUE THREAD

**Issue by ethancowardhive** [astral-sh/ruff-vscode#640]
I noticed that when trying to enable ruff formatting in Jupyter notebooks with import sorting enabled as well, the Ruff native server doesn't correctly format the cells, leading to garbled imports and sometimes completely missing lines of code.

When I change `"ruff.nativeServer": true` to `"ruff.nativeServer": false` to disable the native server, format on save works correctly without any problem.

`ruff.toml`:
```toml
line-length = 120

[lint]
extend-safe-fixes = ["E712", "E711"]
```

`.vscode/settings.json`
```json
{
    "editor.formatOnSave": true,
    "[python]": {
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.codeActionsOnSave": {
            "source.organizeImports": "explicit"
        }
    },
    "ruff.nativeServer": true,
    "notebook.formatOnSave.enabled": true,
    "notebook.codeActionsOnSave": {
        "source.organizeImports": "explicit"
    },
    "notebook.defaultFormatter": "charliermarsh.ruff",
    "ruff.trace.server": "verbose"
}
```

Environment details:
Extension version: `v2024.54.0`
Extension uses Ruff version: `0.7.1`
VS Code version: `1.95.1`
OS: MacOS Sequoia `15.1`
Python Version: `3.12.7`

Code sample:

A new blank notebook with this example code in 2 cells:

```py
from typing import Optional
from typing import Literal
from typing import TypedDict

# Comment
Test = Literal["test"]
```

Note: the code doesn't have to be the same in both cells, and it doesn't have to just be 2 cells in the notebook, but this is a minimal example I've found where the issue happens. The issue doesn't seem to happen when there is just 1 cell in the notebook.

<details>
<summary>Raw json contents of notebook:</summary>
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Optional\n",
    "from typing import Literal\n",
    "from typing import TypedDict\n",
    "\n",
    "# Comment\n",
    "Test = Literal[\"test\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Optional\n",
    "from typing import Literal\n",
    "from typing import TypedDict\n",
    "\n",
    "# Comment\n",
    "Test = Literal[\"test\"]"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```
</details>

Extension logs: https://pastebin.com/pvXc9HZY

Video (with native server enabled):

https://github.com/user-attachments/assets/0a1fa40d-20e4-47a7-b7a2-b25516d5f4aa

Video (with native server disabled):

https://github.com/user-attachments/assets/5173747f-a94e-4c08-96e5-df5104310ea2

If you need any more information or need to clarify anything else with me please let me know, thanks.

**Comment by dhruvmanila** [comment]
Do you have any other extension that support organizing imports? Can you try using `source.organizeImports.ruff` in your VS Code settings instead so that the client only sends the request to Ruff extension?

**Comment by MichaReiser** [comment]
I wonder if this is a problem because we process both the format and organize imports requests concurrently (we don't synchronize on the document). VS code then e.g. updates the format changes first before applying the organize import actions or the other way round. I expected the format response to contain the document version but it doesn't.

**Comment by MichaReiser** [comment]
Same for code actions. There's also this comment

https://github.com/astral-sh/ruff/blob/b72d49be16d5e42fec3d25b33f717f553c8f09b3/crates/ruff_server/src/edit.rs#L139-L141

**Comment by dhruvmanila** [comment]
The difference between the two is that for `source.organizeImports.ruff`, VS Code will send parallel requests to the server for _each_ cell which is where the problem lies. For this specific reason, the VS Code team added support for `notebook.*` prefixed code actions so that it only sends the request once for the entire notebook.

**Comment by ethancowardhive** [comment]
Yeah that seems to fix it, thanks! 

Sorry for raising this since it wasn't actually an issue (and I've just found [documentation](https://github.com/astral-sh/ruff-vscode/blob/main/README.md#configuring-vs-code) that would've fixed it myself...), but thank you anyway for responding so quickly and helping me!

**Comment by dhruvmanila** [comment]
No worries, glad to help. I'll mark this as resolved but feel free to ask any other questions that you might have.
