### ISSUE TITLE
Cannot disable `force-exclude`

### ISSUE THREAD

**Issue by jvacek** [astral-sh/ruff-vscode#641]
Hi there,

I have a ruff config that I'd like to have enforced in CI/CD and with pre-commit, but I'd like to make sure that even files that I've marked as excluded are still within the scope of what the ruff extension in vscode can work with.

I've tried passing `--no-force-exclude` via args and my pyproject.toml, but it seems that neither of these get ingested into the VSCode setup.

Looking at the ouptut, it seems that `force-exclude` is being hard-set, without any way to opt-out, as I see the following in my output?

```
Running Ruff with: /Users/jvacek/.pyenv/versions/usermanagement/bin/ruff ['check', '--force-exclude', '--no-cache', '--no-fix', '--quiet', '--output-format', 'json', '-', '--stdin-filename', '/Users/jvacek/repositories/...'
```
Would appreciate the ability to disable the `--force-exclude` being passed by default.

Thanks!

**Comment by MichaReiser** [comment]
Could you try using the new rust based lsp? See [`nativeServer`](https://docs.astral.sh/ruff/editors/settings/#nativeserver)
