### ISSUE TITLE
Question: How to configure ruff source directory in vscode for sorting imports?

### ISSUE THREAD

**Issue by DanielBoxer** [astral-sh/ruff-vscode#650]
I'm working in a monorepo, so auto formatters aren't able to distinguish absolute path imports from external package imports, and they get grouped together. 

With isort and black, I would set the source directory like this in `.vscode/settings.json` so it would group them separately:

```json
{
    "isort.args": [
        "--src",
        "path/to/source/dir",
        "--profile",
        "black",
    ]
}
```

How can this be done with ruff?

**Comment by dhruvmanila** [comment]
I think that should be done via the [`src`](https://docs.astral.sh/ruff/settings/#src) setting in your Ruff configuration file. In an editor context, the server should pickup the settings. If you want to have a common settings for multiple projects, you could use the [`ruff.configuration`](https://docs.astral.sh/ruff/editors/settings/#configuration) option and specify that in your VS Code settings.

**Comment by DanielBoxer** [comment]
Thanks, this works!
