### ISSUE TITLE
Ruff not recognized as Python formatter by vscode

### ISSUE THREAD

**Issue by JeroenDelcour** [astral-sh/ruff-vscode#652]
Starting about a month ago, when I try to format a Python file, I get an error popup saying:

> Extension 'Ruff' is configured as formatter but it cannot format 'Python'-files

When setting the default formatter in vscode settings, ruff is not shown as an option. Black, which is also installed, shows up and works fine.

The "Ruff: Format document" command shows up in the command palette, but doesn't appear to do anything.

I'm on Ubuntu running the latest version (2024.56.0). I've tried downgrading to old versions (2024.50.0 and even 2024.26.0) with no luck. I've even completely uninstalled vscode, deleted all user settings and extensions directories, and reinstalled only Ruff - it said no Python formatter is installed.

Ruff logs don't show anything out of the ordinary, as far as I can tell:

```
2024-12-12 08:48:08.795 [info] Name: Ruff
2024-12-12 08:48:08.795 [info] Module: ruff
2024-12-12 08:48:08.795 [info] Python extension loading
2024-12-12 08:48:08.795 [info] Waiting for interpreter from python extension.
2024-12-12 08:48:08.795 [info] Python extension loaded
2024-12-12 08:48:08.795 [info] Using interpreter: /home/jeroen/.pyenv/versions/3.11.4/bin/python
2024-12-12 08:48:08.799 [info] Using environment executable: /home/jeroen/.pyenv/shims/ruff
```

Possibly related issues: #460 and #596

**Comment by Real-Gecko** [comment]
I have the same issue when working on remote SSH workspace
![Image](https://github.com/user-attachments/assets/a2985466-dbcb-4cf2-b395-7b342fb8fa67)
Might be related to #178

**Comment by MichaReiser** [comment]
@Real-Gecko Can you try `Ctrl+P` - `Python: Select Interpreter`, then select a "valid python interpreter"?

**Comment by Real-Gecko** [comment]
It's selected, see the small blue screenshot in previous message :D

Ok, I've been able to pinpoint the issue: if I open multiroot workspace on remote server Ruff does not work, however if I just open folder(root folder where `.code-workspace` is) Ruff starts working.

**Comment by JeroenDelcour** [comment]
> [@JeroenDelcour](https://github.com/JeroenDelcour) It seems you are using ruff from environment, which maybe old/unsupported version, can you give output of `/home/jeroen/.pyenv/shims/ruff version`?
> 
> Also try this setting, and see if issue still persists:
> 
> {
>   "ruff.importStrategy": "useBundled"
> }

Thanks, the problem was indeed with the shim pointing to a different ruff version from another Python virtualenv. It was the latest ruff version (0.8.3), though, so I'm not sure why it didn't work. In any case, your setting fixed it. I ended up removing the virtualenv (wasn't using it anymore anyway), which had the same effect of falling back to the bundled ruff version.

Thanks for the quick help!

I'll close this issue, since my original problem is resolved. @Real-Gecko if you're still having problems you might want to open a new issue.
