### ISSUE TITLE
Ruff VSCode plugin constantly pops up error notification when server restarts

### ISSUE THREAD

**Issue by kdowney-talos** [astral-sh/ruff-vscode#656]
If the server restarts, there is always a notification:

<img width="469" alt="Image" src="https://github.com/user-attachments/assets/b5e55d06-a186-4680-ab19-f06481a6f13a" />

If you then view Logs, there are no errors, just "info" level messages about the restart:

<img width="871" alt="Image" src="https://github.com/user-attachments/assets/7d4ab9c8-611c-484b-87e5-fc14dda201d9" />

Notably, this setting:

```
"ruff.showNotifications": "onError"
```

does not appear to matter: whatever it's set to "off" or "onError" or "always" the popup always comes up. In fact, this can be triggered very simply by just doing the `Ruff: Restart Server` command. It also happens spontaneously, which is the annoyance: e.g. on window reloads, or if a configuration changes, or anything else causing server to restart triggers this noise alert.

**Comment by MichaReiser** [comment]
I suspect there's a malformed configuration somewhere, but we aren't doing a good job of surfacing the error. @dhruvmanila plans to improve the error reporting in the next few weeks. So, hopefully, the logs will become more useful by default. 

For now, can you try increasing the trace level as explained [here](https://github.com/astral-sh/ruff-vscode?tab=readme-ov-file#troubleshooting). You should then see more logs, and I'd expect that there's a configuration related message somewhere

**Comment by kdowney-talos** [comment]
Yep, you're right! 

```
2024-12-20 13:27:48.269 [info] [Trace - 1:27:48 PM]    0.153327917s ERROR ThreadId(09) ruff_server::session::index::ruff_settings: Failed to resolve settings for /workspaces/pms/tools/xxx/pyproject.toml: Failed to read /workspaces/pms/tools/build-support/ruff.toml: No such file or directory (os error 2)
```

It looks like Ruff native is checking pyproject.toml first, and I happened to have a single monorepo that had a bad relative path to our shared `ruff.toml` in the root folder. This caused server to error whenever it restarted. 

Note as well there *was* also this setting:

```
"ruff.configuration": "${workspaceFolder}/build-support/ruff.toml",
```

but for some reason it was still referencing `pyproject.toml` module-by-module.

**Comment by MichaReiser** [comment]
> but for some reason it was still referencing pyproject.toml module-by-module.

I'm not sure I understand what you mean by that. Do you mean that Ruff kept discovering the configurations even though you set the setting?


> Yep, you're right!

Nice, is there anything more you need or are you okay if I close the issue?

**Comment by kdowney-talos** [comment]
What I meant was: there was a setting pointing it to a specific `ruff.toml` in VSCode's `settings.json`, but the error was triggered by a bad Ruff setting embedded in one of the `pyproject.toml` in the repo. My expectation would be that it would first look to an explicit configuration path and not auto-discover others. The error was real; I was just surprised it hit a code path where the error would become visible!

**Comment by carnerero** [comment]
Hi! I think it must be reopen. I started to see this error the last week and I have been looking for that configuration option and I has not been able to locate it. I also uninstalled and reinstalled the VSCode extension and my project are using latest ruff version.

![Image](https://github.com/user-attachments/assets/e3006c1a-19fd-4f54-b04f-71559378adf4)

**Comment by dhruvmanila** [comment]
@carnerero Can you try this (https://github.com/astral-sh/ruff/discussions/15991?sort=new#discussioncomment-12161407) ? As the message states, the setting `ruff.showNotifications` is deprecated and should be removed.

**Comment by carnerero** [comment]
> [@carnerero](https://github.com/carnerero) Can you try this ([astral-sh/ruff#15991](https://github.com/astral-sh/ruff/discussions/15991)) ? As the message states, the setting `ruff.showNotifications` is deprecated and should be removed.

Thank you! Opening as JSON I found it.
