### ISSUE TITLE
"ignore" rules with glob patterns incompatible with absolute file paths used to run native server

### ISSUE THREAD

**Issue by shaunc** [astral-sh/ruff-vscode#657]
I have the following config in my pyproject.toml:
```toml
[tool.ruff.lint.per-file-ignores]
# ignore bugbear for jupytext files
"jupyter/*" = ["B"]

# ignore in tests
"{tests,src/timbuktu/testutil}/**/*.py" = [
  "D", # doc
  "S101", # assert
  "T201", # print
  "PLR2004", # magic values (e.g. 0, 1)
  "TID252", # Prefer absolute imports over relative imports from parent modules
  "ARG001", # Unused function argument
]
```
This works (e.g. "assert" is ignored in test files, when ruff is used with paths relative to the working tree root. E.g. the following works:
```sh
$ ruff check --force-exclude --no-cache --no-fix --quiet --output-format json - --config pyproject.toml --stdin-filename tests/datatypes/graph/test_nursery.py < tests/datatypes/graph/te
st_nursery.py 
[]
```
However, looking at logs, the plugin uses a command line like this:
```sh
$ ruff check --force-exclude --no-cache --no-fix --quiet --output-format json - --config pyproject.toml --stdin-filename /home/shauncutts/src/factfiber.ai/learn/timbuktu/tests/datatypes/graph/test_nursery.py < tests/datatypes/graph/test_nursery.py 
[
  {
    "cell": null,
    "code": "S101",
    "end_location": {
      "column": 11,
      "row": 22
    },
    "filename": "/home/shauncutts/src/factfiber.ai/learn/timbuktu/tests/datatypes/graph/test_nursery.py",
    "fix": null,
    "location": {
      "column": 5,
      "row": 22
    },
    "message": "Use of `assert` detected",
    "noqa_row": 22,
    "url": "https://docs.astral.sh/ruff/rules/assert"
  },
  ...
]
```
I have tried putting a "glob" on the beginning of the ingore pattern, but this doesn't work (perhaps two "**" groups are not allowed?) Could we have a configuration to pass relative and not absolute paths to ruff?

**Comment by MichaReiser** [comment]
Can you try using the new "native LSP" over the older "ruff-LSP"? See [using the native server](https://github.com/astral-sh/ruff-vscode?tab=readme-ov-file#using-the-rust-based-language-server) section on how to enable the rust based server implementation

**Comment by shaunc** [comment]
Aha -- that works -- thank you!

In fact, I had "auto" set and thought that meant I was using the native server (so tried explicitly disabling it to test). But I was also specifying config via a command line argument -- which is a "unused by the native language server" setting.

Closing issue.

(I didn't read: -- from doc:)

> None of the settings that are exclusive to the Python-based language server are enabled (i.e., those that are marked as "unused by the native language server" in the [Settings](https://docs.astral.sh/ruff/editors/settings/#vs-code-specific) documentation).
